import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const translations = {
  en: {
    // Nav / Sidebar
    dashboard: "Dashboard",
    workspace: "Workspace",
    adminPortal: "Admin Portal",
    appointments: "Appointments",
    records: "Medical Records",
    chat: "Chat Workspace",
    settings: "Settings",
    imaging: "Imaging Diagnostics",
    logout: "Logout",
    assistant: "HealthAI Assistant",
    role: "Role",
    sosTrigger: "Trigger Clinical SOS",
    sosActive: "SOS Broadcast Active!",
    sosSending: "Activating Emergency...",
    switchToAdmin: "Switch to Admin Mode",
    switchToUser: "Switch to User Mode",
    switchToDoctor: "Switch to Doctor Mode",
    switchToCaregiver: "Switch to Caregiver Mode",
    
    // Patient Dashboard
    welcomeBack: "Welcome back,",
    syncRecords: "Your clinical health records and appointments are fully synchronized.",
    bookVisit: "Book Visit",
    uploadRecords: "Upload Records",
    upcomingAppts: "Upcoming Appointments",
    noAppts: "No upcoming appointments booked.",
    findDocToBook: "Find a Doctor to Book Now",
    cancel: "Cancel",
    aiIntel: "AI Clinical Intelligence",
    aiTip: "AI Tip",
    recordsFolder: "Medical Records Folder",
    recordCount: "files uploaded",
    noRecords: "No medical records found.",
    dateLabel: "Date",
    timeLabel: "Time",
    doctorLabel: "Doctor",
    specializationLabel: "Specialization",
    symptomsLabel: "Symptoms",
    symptomAnalyzer: "Quick Symptom Checker",
    analyzeBtn: "Analyze Symptoms",
    severityLabel: "Severity",
    durationLabel: "Duration",
    
    // Chat Page
    searchContacts: "Search contacts to chat...",
    availableContacts: "Available Contacts",
    activeConvs: "Active Conversations",
    noConvs: "No conversations yet. Type in search above to start one!",
    selectChat: "Select a Chat Conversation",
    consultationWorkspace: "Workspace",
    typeMessage: "Type a message or describe attached documents...",
    send: "Send",
    attachment: "Attachment",
    
    // Doctor Dashboard
    clinicSchedule: "Clinic Schedule",
    patientQueue: "Patient Queue",
    activeAlerts: "Active Emergency Alerts",
    noAlerts: "No emergency alerts reported.",
    resolveAlert: "Resolve Alert",
    patientName: "Patient Name",
    reason: "Reason",
    actions: "Actions",
    
    // Admin Dashboard
    complaintsRegistry: "Complaints & Support Registry",
    resolved: "Resolved",
    pending: "Pending",
    systemUsers: "Registered System Users",
    toggleStatus: "Toggle Status",
    active: "Active",
    inactive: "Inactive",
    grantAdmin: "Grant Admin Switch Permission",
    revokeAdmin: "Revoke Admin Switch Permission",
    adminAllowed: "Admin Mode Switch Granted",
    adminNotAllowed: "Admin Mode Switch Denied",

    // General Layout
    loadingText: "HealthAI is loading...",
    searchDocPlaceholder: "Search doctors by name or specialization...",
    uploadBtn: "Upload Medical PDF/Image",
    allRecords: "All Uploaded Records",

    // Feedback System
    feedbackTitle: "Consultation Feedback & Review",
    editFeedback: "Edit Feedback",
    submitFeedback: "Submit Feedback",
    overallRating: "Overall Consultation Rating",
    doctorRating: "Doctor Professional Rating",
    commentsLabel: "Written Comments & Experience Details",
    commentsPlaceholder: "Write about your experience with the doctor and consultation...",
    ratingCommunication: "Communication Style",
    ratingProfessionalism: "Professional Ethics & Skill",
    ratingWaitTime: "Waiting Time & Schedule Adherence",
    ratingSatisfaction: "Overall Service Satisfaction",
    optionalCategories: "Detailed Ratings (Optional)",
    privacyDisclaimer: "Your comments and detailed ratings are shared with the doctor and public profiles anonymously to protect your privacy.",
    feedbackSubmitted: "Feedback submitted successfully! Thank you for your review.",
    noPendingFeedback: "No consultations pending feedback.",
    feedbackFormError: "Please ensure overall and doctor ratings are selected.",
    completeVisit: "Complete Visit",
    feedbackAnalytics: "Feedback Analytics & Reviews",
    reviewsCount: "reviews",
    anonymousReview: "Verified Patient",
    averageRatingLabel: "Average Rating",
    viewReviewsBtn: "View Reviews",
    moderateReviewsTab: "Review Moderation",
    approveBtn: "Approve",
    noReviewsMsg: "No reviews submitted yet.",
    
    // TARS Voice Assistant
    tarsGreetingInitial: "Hello! I am TARS, your multilingual AI assistant. I can speak and listen in English, Hindi (हिन्दी), Telugu (తెలుగు), Hinglish, and Tinglish. Say \"TARS wake up\" or click the mic to begin, or type a request to navigate through the application.",
    tarsListening: "Yes, I am listening.",
    tarsGoodbye: "Goodbye.",
    tarsError: "Sorry, I encountered an error. Please try again.",
    tarsLoginWarning: "Hello! Please login or register to access fully voice-automated TARS assistance.",
    tarsVoiceCallWarning: "Voice assistant is disabled during an active video call.",
    tarsUnsupported: "SpeechRecognition / Web Speech API is not supported or is disabled in your browser. Please use Chrome or Edge, or enable voice/microphone support in your browser settings.",
    tarsMicDenied: "Microphone access was denied. Please enable microphone permissions in your browser settings to speak to TARS.",
    tarsDeactivatePhrases: "tars go to sleep,tars sleep,tars turn off,turn off tars,tars stop,stop tars,tars deactivate,tars bye,bye tars,go to sleep tars,sleep tars,that's enough,go quiet,stop listening,bye,goodbye,silent,go silent,standby,thank you,thanks,no thanks,no thank you,that's all,that is all,nothing else,end conversation,quit,that's it,thats it",
    tarsWakeWords: "tars,tarz,wake up tars,ok tars,hello tars,hey tars,tars wake up",
    tarsClose: "Close TARS",
    tarsThinking: "TARS is thinking...",
    tarsListeningStatus: "TARS is listening... Speak now",
    tarsSpeakingStatus: "TARS is speaking...",
    tarsActiveStatus: "TARS Voice Standby is Active",
    tarsDisabledStatus: "TARS Voice Standby is Disabled",
    tarsStandbyActive: "Standby: Active",
    tarsStandbyDisabled: "Standby: Disabled",
    tarsTurnOff: "Turn OFF",
    tarsTurnOn: "Turn ON",
    tarsThinkingLabel: "Thinking...",
    tarsSuggestionFindDoctor: "🔍 Find Doctor",
    tarsSuggestionBookVisit: "📅 Book Visit",
    tarsSuggestionViewRecords: "📂 View Records",
    tarsSuggestionFileComplaint: "⚠️ File Complaint",
    tarsInputPlaceholder: "Ask TARS anything...",
    tarsSuggestionFindDoctorText: "Find general doctors",
    tarsSuggestionBookVisitText: "Book appointment",
    tarsSuggestionViewRecordsText: "View my medical records",
    tarsSuggestionFileComplaintText: "I want to submit a complaint",
    
    // Doctor Workspace Dashboard Details
    workspaceSubtitle: "Manage active patient emergencies, upcoming consultations, and clinical records.",
    totalPatients: "Total Patients",
    todaysVisits: "Today's Visits",
    pendingConsults: "Pending Consults",
    averageRatingLabel: "Average Rating",
    patientsDirectory: "Patients Directory",
    upcomingConsultations: "Upcoming Consultations",
    urgentSurgeryReassign: "Urgent Surgery: Reassign",
    noApptsScheduled: "No upcoming patient visits scheduled.",
    noPatientsRegistered: "No patients registered in the directory.",
    submitLeaveRequest: "Submit Leave Request",
    startDate: "Start Date",
    endDate: "End Date",
    reasonLabel: "Reason",
    reasonPlaceholder: "e.g. Attending conference, urgent medical leave",
    submitRequestBtn: "Submit Request",
    leaveRequestsLog: "Leave Requests Log",
    approvedStatus: "approved",
    pendingStatus: "pending",
    rejectedStatus: "rejected",
    
    // Consultation Reminders
    consultationReminders: "Consultation Reminders",
    patientNameLabel: "Consultation / Patient Name",
    patientNamePlaceholder: "e.g. Patient: John Doe",
    prepNotesLabel: "Preparation / Notes",
    prepNotesPlaceholder: "e.g. Review heart logs",
    timeLabel: "Time",
    notifyViaLabel: "Notify Via",
    noConsultationRemindersConfigured: "No consultation reminders configured.",
    
    // Profile Settings Page
    profileSettings: "Profile Settings",
    profileSettingsSubtitle: "Modify your personal settings, health attributes, and contact address details.",
    fullName: "Full Name",
    dob: "Date of Birth",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    heightCm: "Height (cm)",
    weightKg: "Weight (kg)",
    allergies: "Allergies",
    existingConditions: "Existing Medical Conditions",
    homeAddress: "Home Address (Required for Emergency SOS Broadcasting)",
    doctorIdLicense: "Doctor ID / License Number *",
    clinicLocationRoom: "Clinic Location Room",
    specialization: "Specialization",
    experienceYears: "Experience (Years)",
    clinicFullAddress: "Clinic Full Address",
    clinicGpsLocation: "Clinic GPS Location (For emergency SOS routing)",
    latitude: "Latitude",
    longitude: "Longitude",
    getGpsLocation: "Get GPS Location",
    uploadLicenseDoc: "Upload New Medical License Document (PDF/Image) *",
    licenseResetWarning: "Uploading a new license resets your credentials verification back to pending.",
    chooseLicense: "Choose medical license...",
    browse: "Browse",
    activeLicense: "Active License Document",
    currentLicense: "Current",
    uploadProfilePhoto: "Upload New Profile Photo",
    chooseProfilePhoto: "Choose profile photo...",
    adminFullName: "Admin Full Name",
    workOfficeAddress: "Work / Office Address",
    saveProfile: "Save Profile",
    saving: "Saving...",
    profileLoadFailed: "Failed to load profile settings.",
    profileSaveSuccess: "Profile details saved successfully!",
    settingsUpdateFailed: "Failed to update settings.",
    elevatePrivileges: "Elevate Account Privileges",
    elevateSubtitle: "Request promotion to an Administrator role. Administrators can manage users, check verification statuses, and review clinical logs. Requests must be approved by the system superadmin.",
    requestPending: "Promotion Request Pending Approval",
    requestAdminPromotion: "Request Admin Role Promotion",
    promotionRequestSuccess: "Promotion request sent successfully!",
    promotionRequestFailed: "Failed to submit promotion request.",
    themePersonalization: "Theme & Personalization",
    themeSubtitle: "Select your preferred interface color palette. The settings will apply globally across all doctor, patient, and administration spaces.",
    brandPrimaryColor: "Brand Primary Color",
    secondaryAccentColor: "Secondary Accent Color",
    portalBgColor: "Portal Background Color",
    dashboardSurfaceColor: "Dashboard Surface Color",
    livePalettePreview: "Live Palette Preview",
    sampleDashboardElement: "Sample Dashboard Element",
    sampleDashboardDesc: "Derived container styling and readable text overlays will dynamically adjust to your choice.",
    sampleButton: "Sample Button",
    applyCustomTheme: "Apply Custom Theme Settings",
    
    // Theme options
    classicBlue: "Classic Blue",
    classicBlueDesc: "Soothing professional blue",
    midnightNavy: "Midnight Navy",
    midnightNavyDesc: "Low-light dark mode",
    forestTeal: "Forest Teal",
    forestTealDesc: "Fresh clinical mint",
    royalViolet: "Royal Violet",
    royalVioletDesc: "Creative accent purple",
    warmRose: "Warm Rose",
    warmRoseDesc: "Warm comforting rose",
    customStudio: "Custom Studio",
    customStudioDesc: "Design your own theme palette",
    
    // Doctor Specializations
    "Cardiology": "Cardiology",
    "Dermatology": "Dermatology",
    "General Medicine": "General Medicine",
    "Neurology": "Neurology",
    "Pediatrics": "Pediatrics",
    
    // Landing / Hero Elements
    trustBadge: "Next-Gen Medical Intelligence",
    heroTitle: "Healthcare Reimagined with AI",
    heroSubtext: "Connect with practitioners, analyze diagnostics reports, check symptoms instantly, and manage your medical records through an intelligent, HIPAA-compliant patient dashboard.",
    btnGetStarted: "Get Started Free",
    btnExploreFeatures: "Explore Features",
    
    // Mockup Card Translations
    mockupHeartRate: "Live Heart Rate",
    mockupHealthIndex: "Health Index",
    mockupVitalsStatus: "Vitals stable. Activity levels are optimal. Sleep quality rose 8% this week.",
    mockupReportDissection: "AI Report Dissection",
    mockupAnalysisDesc: "Clinical Analysis: CBC report shows mild iron-deficiency anemia (Hb: 10.8 g/dL). Sleep disruption noted. Recommended iron-rich diet & schedule virtual checkup.",
    mockupHbLabel: "Hb: 10.8 g/dL (Low)",
    mockupFerritinLabel: "Ferritin: 12 ng/mL",
    mockupActionReq: "Action Required",
    mockupConnected: "Connected",
    
    // Landing Core Features
    landingCapabilities: "Capabilities",
    landingIntelligentHealth: "Intelligent Health Services",
    landingServicesSubtitle: "Discover a unified platform designed to streamline diagnostic triaging, clinical communications, and daily medical logs.",
    featureTriage: "Triage",
    featureTriageTitle: "AI Symptom Checker",
    featureTriageDesc: "Analyze symptoms and receive instant, personalized triage advice with list of potential causes powered by secure medical AI.",
    featureTelemed: "Telemedicine",
    featureTelemedTitle: "Virtual Consultation",
    featureTelemedDesc: "Consult directly with certified healthcare professionals via low-latency, HIPAA-compliant video calls and private chat sessions.",
    featureRxSafety: "Rx Safety",
    featureRxSafetyTitle: "Medication Management",
    featureRxSafetyDesc: "Set smart pill reminders, track dosage history, and receive automated warnings for drug-to-drug interactions.",
    featureDiag: "Diagnostics",
    featureDiagTitle: "Report Analysis",
    featureDiagDesc: "Dissect complex lab reports or test documents instantly to receive plain-language summaries of medical terminology.",
    featureVitals: "Vitals Sync",
    featureVitalsTitle: "Health Monitoring",
    featureVitalsDesc: "Sync and track wearable health data including heart rates, step logs, blood oxygen levels, and weekly sleep analytics.",
    featureEmergency: "24/7 Care",
    featureEmergencyTitle: "Emergency Guidance",
    featureEmergencyDesc: "Instant access to emergency protocols, first-aid directives, and immediate routing to the nearest hospital facility.",
    learnMore: "Learn more",
    
    // Landing Stats
    statCheckerAccuracyVal: "99.4%",
    statCheckerAccuracyLbl: "AI Checker Accuracy",
    statConsultationsVal: "150k+",
    statConsultationsLbl: "Consultations",
    statResponseVal: "<2 Min",
    statResponseLbl: "Average Response",
    statArchitectureVal: "HIPAA",
    statArchitectureLbl: "Compliant Architecture",
    
    // Sliding Text Section
    slidingLine1: "Built for doctors.",
    slidingLine2: "Designed for patients.",
    slidingLine3: "Powered by AI.",
    
    // Testimonials
    testimonialTitle: "Testimonials",
    testimonialSubtitle: "Trusted by Doctors & Patients",
    testimonialDesc: "Hear from qualified clinical specialists and active patients using HealthAI.",
    testimonialVanceQuote: "\"HealthAI has transformed the way I connect with my patients. The automated AI report analysis saves hours of manual diagnostic reading, allowing me to focus on high-impact treatments during virtual calls.\"",
    testimonialVanceName: "Dr. Alisha Vance, MD",
    testimonialVanceRole: "Chief of Cardiology, Vanguard Health",
    testimonialJenkinsQuote: "\"The AI symptom checker is absolutely incredible. It gave my family clear triage advice when my son had a high fever at midnight, helping us understand whether to wait or head to the emergency room.\"",
    testimonialJenkinsName: "Sarah Jenkins",
    testimonialJenkinsRole: "Verified Platform User since 2024",
    
    // Footer
    footerBrandDesc: "Next-generation diagnostic checkers, clinical consultation portals, and secure patient timeline indexing.",
    footerFeatures: "Features",
    footerCompliance: "Compliance",
    footerSupport: "Support",
    footerDisclaimer: "Disclaimer: HealthAI symptom checker provides diagnostic triaging advice for informational purposes only. It does not replace the professional clinical judgment, physical examination, or treatment recommendation of a certified medical practitioner.",
    footerCopyright: "© 2026 HealthAI Inc. All rights reserved.",
    
    // Security Section
    secTitle: "Security",
    secHeading: "Enterprise-grade Clinical Security",
    secDesc: "HealthAI is built from the ground up on modern cryptographic database frameworks, prioritizing user privacy, strict access logs, and complete compliance.",
    tagHipaa: "HIPAA Compliant",
    tagSoc2: "SOC2 Audited",
    tagGdpr: "GDPR Safeguarded",
    cardEncTitle: "End-to-End Encryption",
    cardEncDesc: "All communications and uploaded records are encrypted in transit and at rest using AES-256 standards.",
    cardAccTitle: "Access Control",
    cardAccDesc: "Granular role-based security settings ensure only authorized doctors and patients can access medical files.",
    cardAudTitle: "Audit Trails",
    cardAudDesc: "Every document access, consultation link, and diagnostic query is recorded in immutable compliance logs.",
    cardApiTitle: "Secure API Routing",
    cardApiDesc: "All external communication routes are authenticated using OAuth2 and signed cryptographic JSON web tokens.",

    // Footer Links
    footerComplianceStd: "Compliance Architecture Standards",
    footerSoc2: "SOC2 Audits",
    footerKeyMgmt: "Encryption Key Management",
    footerAuditRecs: "Audit Records",
    footerKnowledgeBase: "Knowledge Base",
    footerClinicDir: "Clinic Directory",
    footerContactSupport: "Contact Support",
    footerFileComplaint: "File Complaint",
    
    // Authentication Pages (Login, Register, OTP Verify)
    authTitle: "Precision Intelligence for Human Wellness.",
    authDesc: "Access your clinical dashboard, patient records, and AI-driven diagnostic tools with enterprise-grade security.",
    loginHeader: "Welcome Back",
    loginSubtitle: "Sign in to access your clinical dashboard",
    labelEmail: "Email Address",
    labelPassword: "Password",
    labelConfirmPassword: "Confirm Password",
    placeholderEmail: "e.g. physician@healthai.org",
    placeholderPassword: "••••••••",
    btnSignIn: "Sign In",
    btnForgot: "Forgot password?",
    textNoAccount: "Don't have an account?",
    textHaveAccount: "Already have an account?",
    linkRegister: "Register now",
    linkLogin: "Log in instead",
    forgotHeader: "Reset Password",
    forgotSubtitle: "Request temporary verification code to recover access",
    btnSendCode: "Send Code",
    btnVerifyCode: "Verify Code",
    btnBackToLogin: "Back to Sign In",
    otpHeader: "Enter Verification Code",
    otpSubtitle: "We've dispatched a 6-digit security code to your email.",
    otpEnterMsg: "Please enter all 6 digits",
    btnVerify: "Verify Code",
    btnResendOtp: "Resend Code",
    registerTitle: "Create Account",
    registerSubtitle: "Register a new secure account on the platform",
    tabPatient: "Patient Profile",
    tabDoctor: "Medical Practitioner",
    btnRegister: "Register Profile",
    doctorRegHeadline: "Clinical Practitioner Boarding",
    doctorRegSub: "Specify your license credentials and GPS coordination.",
    doctorRegPlaceholderName: "Dr. Sarah Jenkins",
    doctorRegExp: "Experience (Years)",
    doctorRegLicense: "Medical License / Practitioner ID",
    doctorRegLocation: "Office / Clinic Location Room",
    doctorRegAddress: "Clinic Complete Address",
    doctorRegChooseLicense: "Choose medical license document (PDF/Image)...",
    doctorRegChoosePhoto: "Choose professional profile photo (Image)...",
    doctorRegGps: "GPS Coordinates",
    doctorRegLat: "Latitude",
    doctorRegLng: "Longitude",
    doctorRegGetGps: "Get GPS Location",
    doctorRegMapLoading: "Map loading...",
    forgotSuccessMsg: "A 6-digit verification code has been dispatched to your email address.",
    forgotErrorMsg: "Failed to send verification code. Check email address.",
    forgotVerifyError: "Invalid OTP code. Please retry.",
    loginErrorMsg: "Failed to login. Please check credentials.",
    otpResendSuccess: "A verification code has been resent to your email address.",
    otpResendFailed: "Failed to resend verification code.",
    primaryFindingLabel: "Primary Finding",
    severityLevelLabel: "Severity Level",
    clinicalRecommendationLabel: "Clinical Recommendation",
    confidenceLabel: "Confidence",
    medicineReminders: "Medicine Reminders",
    medicineName: "Medicine Name",
    dosageLabel: "Dosage",
    notifyVia: "Notify Via",
    contactInfoOptional: "Contact Info (Optional)",
    addReminder: "Add Reminder",
    noMedicineRemindersConfigured: "No medicine reminders configured.",
    yourScheduleLog: "Your Schedule Log",
    inAppNotification: "In-App Notification",
    emailAlert: "Email Alert",
    smsAlert: "SMS Alert",
    recentActivity: "Recent Activity",
    allSpecialities: "All Specialities",
    showAvailableOnly: "Show Available Only",
    noSpecialistsFound: "No specialists found matching your filter criteria.",
    yearsExperience: "Years Experience",
    reviews: "reviews",
    locationLabel: "Location",
    emailLabel: "Email",
    addressLabel: "Address",
    clinicalDetailsGuidelines: "Clinical Details & Guidelines",
    available: "Available",
    unavailable: "Unavailable",
    scheduleConsultation: "Schedule Consultation",
    appointmentRequested: "Appointment Requested!",
    appointmentScheduledSuccess: "Your visit has been scheduled successfully.",
    selectConsultationDate: "Select Consultation Date",
    selectTimeSlot: "Select Time Slot",
    noSlotsAvailable: "No slots available for today",
    confirmBooking: "Confirm Booking",
    reviewsFor: "Reviews for",
    specialist: "specialist",
    loadingReviews: "Loading reviews...",
    comm: "Comm",
    ethics: "Ethics",
    recordsSubtitle: "Store, organize, and view your diagnostic reports and medical files with secure backup.",
    yourUploadedRecords: "Your Uploaded Records",
    noMedicalRecords: "No medical records uploaded yet.",
    uploadInstruction: "Select a file on the right side panel to upload your first report.",
    uploadedLabel: "Uploaded",
    scanLabel: "Scan",
    scanning: "Scanning...",
    verified: "Verified",
    runAntiFraud: "Run Anti-Fraud",
    aiInsights: "AI Insights",
    viewFile: "View File",
    delete: "Delete",
    uploadDocument: "Upload Document",
    selectPdfOrImage: "Select PDF or Image file",
    maxSize: "Max size",
    uploadReport: "Upload Report",
    tarsClinicalAiInsights: "TARS Clinical AI Insights",
    analyzing: "Analyzing",
    tarsReadingReport: "TARS is reading your report and consulting medical models...",
    yoloAnalysis: "Diagnostic Scan YOLO Analysis",
    clinicalFindings: "Clinical Findings & Conditions",
    suggestedMedications: "Suggested Medications",
    noAnalysisData: "No analysis data available.",
    autoGenerateReminders: "Auto-generate Reminders",
    generating: "Generating...",
    done: "Done"
  },
  hi: {
    // Nav / Sidebar
    dashboard: "डैशबोर्ड",
    workspace: "कार्यस्थल",
    adminPortal: "एडमिन पोर्टल",
    appointments: "अपॉइंटमेंट",
    records: "चिकित्सा रिकॉर्ड",
    chat: "चैट वर्कस्पेस",
    settings: "सेटिंग्स",
    imaging: "इमेजिंग निदान",
    logout: "लॉगआउट",
    assistant: "हेल्थएआई सहायक",
    role: "भूमिका",
    sosTrigger: "आपातकालीन एसओएस भेजें",
    sosActive: "एसओएस सक्रिय है!",
    sosSending: "एसओएस सक्रिय किया जा रहा है...",
    switchToAdmin: "एडमिन मोड में जाएं",
    switchToUser: "यूज़र मोड में जाएं",
    switchToDoctor: "डॉक्टर मोड में जाएं",
    switchToCaregiver: "केयरगिवर मोड में जाएं",
    
    // Patient Dashboard
    welcomeBack: "आपका स्वागत है,",
    syncRecords: "आपके चिकित्सा रिकॉर्ड और अपॉइंटमेंट पूरी तरह से सिंक हैं।",
    bookVisit: "अपॉइंटमेंट बुक करें",
    uploadRecords: "रिकॉर्ड अपलोड करें",
    upcomingAppts: "आगामी अपॉइंटमेंट",
    noAppts: "कोई आगामी अपॉइंटमेंट बुक नहीं है।",
    findDocToBook: "बुक करने के लिए डॉक्टर खोजें",
    cancel: "रद्द करें",
    aiIntel: "एआई नैदानिक खुफिया",
    aiTip: "एआई टिप",
    recordsFolder: "चिकित्सा रिकॉर्ड फ़ोल्डर",
    recordCount: "फ़ाइलें अपलोड की गईं",
    noRecords: "कोई चिकित्सा रिकॉर्ड नहीं मिला।",
    dateLabel: "तारीख",
    timeLabel: "समय",
    doctorLabel: "चिकित्सक",
    specializationLabel: "विशेषज्ञता",
    symptomsLabel: "लक्षण",
    symptomAnalyzer: "त्वरित लक्षण परीक्षक",
    analyzeBtn: "लक्षणों का विश्लेषण करें",
    severityLabel: "तीव्रता",
    durationLabel: "अवधि",

    // Chat Page
    searchContacts: "चैट करने के लिए संपर्क खोजें...",
    availableContacts: "उपलब्ध संपर्क",
    activeConvs: "सक्रिय बातचीत",
    noConvs: "अभी तक कोई बातचीत नहीं हुई है। संपर्क खोजें!",
    selectChat: "एक चैट बातचीत चुनें",
    consultationWorkspace: "कार्यस्थान",
    typeMessage: "संदेश लिखें या दस्तावेज़ विवरण लिखें...",
    send: "भेजें",
    attachment: "अटैचमेंट",
    
    // Doctor Dashboard
    clinicSchedule: "क्लीनिक अनुसूची",
    patientQueue: "मरीजों की कतार",
    activeAlerts: "सक्रिय आपातकालीन अलर्ट",
    noAlerts: "कोई आपातकालीन अलर्ट नहीं मिला।",
    resolveAlert: "अलर्ट हल करें",
    patientName: "मरीज का नाम",
    reason: "कारण",
    actions: "कार्रवाई",
    
    // Admin Dashboard
    complaintsRegistry: "शिकायत एवं सहायता रजिस्ट्री",
    resolved: "समाधान किया गया",
    pending: "लंबित",
    systemUsers: "पंजीकृत सिस्टम उपयोगकर्ता",
    toggleStatus: "स्थिति बदलें",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    grantAdmin: "एडमिन स्विच अनुमति दें",
    revokeAdmin: "एडमिन स्विच अनुमति वापस लें",
    adminAllowed: "एडमिन मोड अनुमति स्वीकृत",
    adminNotAllowed: "एडमिन मोड अनुमति अस्वीकृत",

    // General Layout
    loadingText: "हेल्थएआई लोड हो रहा है...",
    searchDocPlaceholder: "नाम या विशेषज्ञता के आधार पर डॉक्टरों को खोजें...",
    uploadBtn: "चिकित्सा पीडीएफ/छवि अपलोड करें",
    allRecords: "सभी अपलोड किए गए रिकॉर्ड",

    // Feedback System
    feedbackTitle: "परामर्श प्रतिक्रिया और समीक्षा",
    editFeedback: "प्रतिक्रिया संपादित करें",
    submitFeedback: "प्रतिक्रिया भेजें",
    overallRating: "समग्र परामर्श रेटिंग",
    doctorRating: "डॉक्टर व्यावसायिक रेटिंग",
    commentsLabel: "लिखित टिप्पणियाँ और अनुभव विवरण",
    commentsPlaceholder: "डॉक्टर और परामर्श के अपने अनुभव के बारे में लिखें...",
    ratingCommunication: "संचार शैली",
    ratingProfessionalism: "व्यावसायिक नैतिकता और कौशल",
    ratingWaitTime: "प्रतीक्षा समय और कार्यक्रम का पालन",
    ratingSatisfaction: "समग्र सेवा संतुष्टि",
    optionalCategories: "विस्तृत रेटिंग (वैकल्पिक)",
    privacyDisclaimer: "आपकी गोपनीयता की रक्षा के लिए आपकी टिप्पणियाँ और विस्तृत रेटिंग डॉक्टर और सार्वजनिक प्रोफाइल के साथ गुमनाम रूप से साझा की जाती हैं।",
    feedbackSubmitted: "प्रतिक्रिया सफलतापूर्वक सबमिट की गई! आपकी समीक्षा के लिए धन्यवाद।",
    noPendingFeedback: "कोई परामर्श प्रतिक्रिया के लिए लंबित नहीं है।",
    feedbackFormError: "कृपया सुनिश्चित करें कि समग्र और डॉक्टर रेटिंग चुनी गई हैं।",
    completeVisit: "यात्रा पूरी करें",
    feedbackAnalytics: "प्रतिक्रिया विश्लेषण और समीक्षाएं",
    reviewsCount: "समीक्षाएं",
    anonymousReview: "सत्यापित रोगी",
    averageRatingLabel: "औसत रेटिंग",
    viewReviewsBtn: "समीक्षाएं देखें",
    moderateReviewsTab: "समीक्षा मॉडरेशन",
    noReviewsMsg: "अभी तक कोई समीक्षा सबमिट नहीं की गई है।",
    
    // TARS Voice Assistant
    tarsGreetingInitial: "नमस्ते! मैं TARS हूँ, आपका बहुभाषी AI सहायक। मैं अंग्रेज़ी, हिंदी (हिन्दी), तेलुगु (తెలుగు), हिंग्लिश और टिंग्लिश में बोल और सुन सकता हूँ। शुरू करने के लिए \"TARS wake up\" कहें या माइक पर क्लिक करें, या एप्लिकेशन में नेविगेट करने के लिए अपना अनुरोध टाइप करें।",
    tarsListening: "जी, मैं सुन रहा हूँ।",
    tarsGoodbye: "अलविदा।",
    tarsError: "क्षमा करें, मुझे एक त्रुटि का सामना करना पड़ा। कृपया पुनः प्रयास करें।",
    tarsLoginWarning: "नमस्ते! पूर्ण रूप से वॉयस-ऑटोमेटेड TARS सहायता प्राप्त करने के लिए कृपया लॉगिन या रजिस्टर करें।",
    tarsVoiceCallWarning: "सक्रिय वीडियो कॉल के दौरान वॉयस असिस्टेंट अक्षम रहता है।",
    tarsUnsupported: "इस ब्राउज़र में स्पीच रिकग्निशन समर्थित नहीं है। कृपया क्रोम या एज का उपयोग करें, या ब्राउज़र सेटिंग्स में माइक्रोफ़ोन की अनुमति दें।",
    tarsMicDenied: "माइक्रोफ़ोन का उपयोग अस्वीकार कर दिया गया था। कृपया ब्राउज़र सेटिंग्स में माइक्रोफ़ोन अनुमति सक्षम करें।",
    tarsDeactivatePhrases: "tars go to sleep,tars sleep,tars turn off,turn off tars,tars stop,stop tars,tars deactivate,tars bye,bye tars,tars sojao,tars band karo,tars off karo,tars bandh karo,go to sleep tars,sleep tars,sojao tars,band karo tars,bas karo,bye,goodbye,chup,chup ho jao,chup raho,silent,go silent,standby,dhanyawad,shukriya,bas,aur kuch nahi,kuch nahi,dhanyavaad",
    tarsWakeWords: "tars,tarz,tars chalu,tars kholo,tars sojao,tars utho,utho tars,टार्स,हे टार्स",
    tarsClose: "TARS बंद करें",
    tarsThinking: "TARS सोच रहा है...",
    tarsListeningStatus: "TARS सुन रहा है... अब बोलें",
    tarsSpeakingStatus: "TARS बोल रहा है...",
    tarsActiveStatus: "TARS वॉयस स्टैंडबाय सक्रिय है",
    tarsDisabledStatus: "TARS वॉयस स्टैंडबाय अक्षम है",
    tarsStandbyActive: "स्टैंडबाय: सक्रिय",
    tarsStandbyDisabled: "स्टैंडबाय: अक्षम",
    tarsTurnOff: "बंद करें",
    tarsTurnOn: "चालू करें",
    tarsThinkingLabel: "सोच रहा है...",
    tarsSuggestionFindDoctor: "🔍 डॉक्टर खोजें",
    tarsSuggestionBookVisit: "📅 अपॉइंटमेंट",
    tarsSuggestionViewRecords: "📂 रिकॉर्ड देखें",
    tarsSuggestionFileComplaint: "⚠️ शिकायत दर्ज करें",
    tarsInputPlaceholder: "TARS से कुछ भी पूछें...",
    tarsSuggestionFindDoctorText: "सामान्य डॉक्टर खोजें",
    tarsSuggestionBookVisitText: "अपॉइंटमेंट बुक करें",
    tarsSuggestionViewRecordsText: "मेरे चिकित्सा रिकॉर्ड देखें",
    tarsSuggestionFileComplaintText: "मैं एक शिकायत दर्ज करना चाहता हूँ",
    
    // Doctor Workspace Dashboard Details
    workspaceSubtitle: "सक्रिय रोगी आपातकालीन स्थितियों, आगामी नियुक्तियों और नैदानिक रिकॉर्ड का प्रबंधन करें।",
    totalPatients: "कुल मरीज़",
    todaysVisits: "आज की नियुक्तियाँ",
    pendingConsults: "लंबित परामर्श",
    averageRatingLabel: "औसत रेटिंग",
    patientsDirectory: "रोगी निर्देशिका",
    upcomingConsultations: "आगामी परामर्श",
    urgentSurgeryReassign: "आपातकालीन सर्जरी: पुनः सौंपें",
    noApptsScheduled: "कोई आगामी रोगी नियुक्तियाँ निर्धारित नहीं हैं।",
    noPatientsRegistered: "निर्देशिका में कोई मरीज़ पंजीकृत नहीं हैं।",
    submitLeaveRequest: "अवकाश अनुरोध सबमिट करें",
    startDate: "प्रारंभ तिथि",
    endDate: "समाप्ति तिथि",
    reasonLabel: "कारण",
    reasonPlaceholder: "जैसे: सम्मेलन में भाग लेना, तत्काल चिकित्सा अवकाश",
    submitRequestBtn: "अनुरोध सबमिट करें",
    leaveRequestsLog: "अवकाश अनुरोध लॉग",
    approvedStatus: "स्वीकृत",
    pendingStatus: "लंबित",
    rejectedStatus: "अस्वीकृत",
    
    // Consultation Reminders
    consultationReminders: "परामर्श अनुस्मारक",
    patientNameLabel: "परामर्श / रोगी का नाम",
    patientNamePlaceholder: "जैसे: रोगी: जॉन डो",
    prepNotesLabel: "तैयारी / नोट्स",
    prepNotesPlaceholder: "जैसे: हृदय लॉग की समीक्षा करें",
    timeLabel: "समय",
    notifyViaLabel: "इसके माध्यम से सूचित करें",
    noConsultationRemindersConfigured: "कोई परामर्श अनुस्मारक कॉन्फ़िगर नहीं किया गया है।",
    
    // Profile Settings Page
    profileSettings: "प्रोफ़ाइल सेटिंग्स",
    profileSettingsSubtitle: "अपनी व्यक्तिगत सेटिंग्स, स्वास्थ्य विशेषताओं और संपर्क पते के विवरण को संशोधित करें।",
    fullName: "पूरा नाम",
    dob: "जन्म तिथि",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    heightCm: "ऊंचाई (सेमी)",
    weightKg: "वजन (किग्रा)",
    allergies: "एलर्जी",
    existingConditions: "मौजूदा चिकित्सा स्थितियां",
    homeAddress: "घर का पता (आपातकालीन एसओएस प्रसारण के लिए आवश्यक)",
    doctorIdLicense: "डॉक्टर आईडी / लाइसेंस नंबर *",
    clinicLocationRoom: "क्लिनिक स्थान का कमरा",
    specialization: "विशेषज्ञता",
    experienceYears: "अनुभव (वर्ष)",
    clinicFullAddress: "क्लिनिक का पूरा पता",
    clinicGpsLocation: "क्लिनिक जीपीएस स्थान (आपातकालीन एसओएस रूटिंग के लिए)",
    latitude: "अक्षांश",
    longitude: "रेखांश",
    getGpsLocation: "जीपीएस स्थान प्राप्त करें",
    uploadLicenseDoc: "नया चिकित्सा लाइसेंस दस्तावेज अपलोड करें (पीडीएफ/छवि) *",
    licenseResetWarning: "नया लाइसेंस अपलोड करने से आपकी साख सत्यापन फिर से लंबित हो जाती है।",
    chooseLicense: "चिकित्सा लाइसेंस चुनें...",
    browse: "ब्राउज़ करें",
    activeLicense: "सक्रिय लाइसेंस दस्तावेज",
    currentLicense: "वर्तमान",
    uploadProfilePhoto: "नई प्रोफ़ाइल फ़ोटो अपलोड करें",
    chooseProfilePhoto: "प्रोफ़ाइल फ़ोटो चुनें...",
    adminFullName: "एडमिन का पूरा नाम",
    workOfficeAddress: "काम / कार्यालय का पता",
    saveProfile: "प्रोफ़ाइल सहेजें",
    saving: "सहेजा जा रहा है...",
    profileLoadFailed: "प्रोफ़ाइल सेटिंग्स लोड करने में विफल।",
    profileSaveSuccess: "प्रोफ़ाइल विवरण सफलतापूर्वक सहेजा गया!",
    settingsUpdateFailed: "सेटिंग्स अपडेट करने में विफल।",
    elevatePrivileges: "अकाउंट विशेषाधिकार बढ़ाएं",
    elevateSubtitle: "प्रशासक भूमिका में पदोन्नति का अनुरोध करें। प्रशासक उपयोगकर्ताओं को प्रबंधित कर सकते हैं, सत्यापन स्थिति की जांच कर सकते हैं और नैदानिक लॉग की समीक्षा कर सकते हैं। अनुरोधों को सिस्टम सुपरएडमिन द्वारा अनुमोदित किया जाना चाहिए।",
    requestPending: "पदोन्नति अनुरोध अनुमोदन के लिए लंबित",
    requestAdminPromotion: "प्रशासक भूमिका पदोन्नति का अनुरोध करें",
    promotionRequestSuccess: "पदोन्नति अनुरोध सफलतापूर्वक भेजा गया!",
    promotionRequestFailed: "पदोन्नति अनुरोध सबमिट करने में विफल।",
    themePersonalization: "थीम और वैयक्तिकरण",
    themeSubtitle: "अपना पसंदीदा इंटरफ़ेस रंग पैलेट चुनें। सेटिंग्स सभी डॉक्टर, रोगी और प्रशासन स्थानों पर विश्व स्तर पर लागू होंगी।",
    brandPrimaryColor: "ब्रांड का प्राथमिक रंग",
    secondaryAccentColor: "द्वितीयक उच्चारण रंग",
    portalBgColor: "पोर्टल का पृष्ठभूमि रंग",
    dashboardSurfaceColor: "डैशबोर्ड का सतह रंग",
    livePalettePreview: "लाइव पैलेट पूर्वावलोकन",
    sampleDashboardElement: "नमूना डैशबोर्ड तत्व",
    sampleDashboardDesc: "व्युत्पन्न कंटेनर स्टाइलिंग और पठनीय पाठ ओवरले आपकी पसंद के अनुसार गतिशील रूप से समायोजित होंगे।",
    sampleButton: "नमूना बटन",
    applyCustomTheme: "कस्टम थीम सेटिंग्स लागू करें",
    
    // Theme options
    classicBlue: "क्लासिक ब्लू",
    classicBlueDesc: "सुखदायक पेशेवर नीला",
    midnightNavy: "मिडनाइट नेवी",
    midnightNavyDesc: "कम रोशनी वाला डार्क मोड",
    forestTeal: "फॉरेस्ट टील",
    forestTealDesc: "ताज़ा नैदानिक पुदीना",
    royalViolet: "रॉयल वायलेट",
    royalVioletDesc: "रचनात्मक लहजा बैंगनी",
    warmRose: "वार्म रोज़",
    warmRoseDesc: "गर्म आरामदायक गुलाब",
    customStudio: "कस्टम स्टूडियो",
    customStudioDesc: "अपना खुद का थीम पैलेट डिज़ाइन करें",
    
    // Doctor Specializations
    "Cardiology": "हृदयरोग विज्ञान",
    "Dermatology": "त्वचा विज्ञान",
    "General Medicine": "सामान्य चिकित्सा",
    "Neurology": "न्यूरोलॉजी",
    "Pediatrics": "बाल रोग विज्ञान",
    
    // Landing / Hero Elements
    trustBadge: "अगली पीढ़ी की चिकित्सा बुद्धिमत्ता",
    heroTitle: "एआई के साथ स्वास्थ्य सेवा की नई कल्पना",
    heroSubtext: "चिकित्सकों से जुड़ें, नैदानिक रिपोर्टों का विश्लेषण करें, लक्षणों की तुरंत जांच करें, और एक बुद्धिमान, HIPAA-अनुपालन रोगी डैशबोर्ड के माध्यम से अपने चिकित्सा रिकॉर्ड का प्रबंधन करें।",
    btnGetStarted: "मुफ्त में शुरू करें",
    btnExploreFeatures: "सुविधाओं का पता लगाएं",
    
    // Mockup Card Translations
    mockupHeartRate: "लाइव हृदय गति",
    mockupHealthIndex: "स्वास्थ्य सूचकांक",
    mockupVitalsStatus: "वाइटल्स स्थिर हैं। गतिविधि का स्तर इष्टतम है। इस सप्ताह नींद की गुणवत्ता 8% बढ़ी है।",
    mockupReportDissection: "एआई रिपोर्ट विश्लेषण",
    mockupAnalysisDesc: "नैदानिक विश्लेषण: सीबीसी रिपोर्ट हल्के लोहे की कमी से होने वाले एनीमिया (एचबी: 10.8 ग्राम/डीएल) को दर्शाती है। नींद में खलल दर्ज किया गया। आयरन युक्त आहार की सिफारिश की गई और वर्चुअल चेकअप निर्धारित करें।",
    mockupHbLabel: "एचबी: 10.8 ग्राम/डीएल (कम)",
    mockupFerritinLabel: "फेरिटिन: 12 एनजी/एमएल",
    mockupActionReq: "कार्रवाई आवश्यक",
    mockupConnected: "कनेक्टेड",
    
    // Landing Core Features
    landingCapabilities: "क्षमताएं",
    landingIntelligentHealth: "बुद्धिमान स्वास्थ्य सेवाएं",
    landingServicesSubtitle: "नैदानिक वर्गीकरण, नैदानिक संचार और दैनिक चिकित्सा लॉग को सुव्यवस्थित करने के लिए डिज़ाइन किए गए एक एकीकृत मंच की खोज करें।",
    featureTriage: "वर्गीकरण",
    featureTriageTitle: "एआई लक्षण परीक्षक",
    featureTriageDesc: "सुरक्षित चिकित्सा एआई द्वारा संचालित संभावित कारणों की सूची के साथ लक्षणों का विश्लेषण करें और त्वरित, व्यक्तिगत वर्गीकरण सलाह प्राप्त करें।",
    featureTelemed: "टेलीमेडिसिन",
    featureTelemedTitle: "वर्चुअल परामर्श",
    featureTelemedDesc: "कम विलंबता, HIPAA-अनुपालन वीडियो कॉल और निजी चैट सत्रों के माध्यम से प्रमाणित स्वास्थ्य पेशेवरों के साथ सीधे परामर्श करें।",
    featureRxSafety: "आरएक्स सुरक्षा",
    featureRxSafetyTitle: "दवा प्रबंधन",
    featureRxSafetyDesc: "स्मार्ट पिल अनुस्मारक सेट करें, खुराक के इतिहास को ट्रैक करें, और दवाओं के परस्पर प्रभाव के लिए स्वचालित चेतावनी प्राप्त करें।",
    featureDiag: "निदान",
    featureDiagTitle: "रिपोर्ट विश्लेषण",
    featureDiagDesc: "जटिल लैब रिपोर्ट या परीक्षण दस्तावेजों का तुरंत विश्लेषण करें ताकि चिकित्सा शब्दावली का सरल भाषा में सारांश प्राप्त किया जा सके।",
    featureVitals: "वाइटल्स सिंक",
    featureVitalsTitle: "स्वास्थ्य निगरानी",
    featureVitalsDesc: "हृदय गति, कदम लॉग, रक्त ऑक्सीजन स्तर और साप्ताहिक नींद विश्लेषण सहित पहनने योग्य स्वास्थ्य डेटा को सिंक और ट्रैक करें।",
    featureEmergency: "24/7 देखभाल",
    featureEmergencyTitle: "आपातकालीन मार्गदर्शन",
    featureEmergencyDesc: "आपातकालीन प्रोटोकॉल, प्राथमिक चिकित्सा निर्देशों तक त्वरित पहुंच और निकटतम अस्पताल सुविधा के लिए तत्काल मार्ग मार्गदर्शन।",
    learnMore: "अधिक जानें",
    
    // Landing Stats
    statCheckerAccuracyVal: "99.4%",
    statCheckerAccuracyLbl: "एआई परीक्षक सटीकता",
    statConsultationsVal: "150k+",
    statConsultationsLbl: "परामर्श",
    statResponseVal: "<2 मिनट",
    statResponseLbl: "औसत प्रतिक्रिया",
    statArchitectureVal: "HIPAA",
    statArchitectureLbl: "अनुपालन वास्तुकला",
    
    // Sliding Text Section
    slidingLine1: "डॉक्टरों के लिए बनाया गया।",
    slidingLine2: "मरीजों के लिए डिज़ाइन किया गया।",
    slidingLine3: "एआई द्वारा संचालित।",
    
    // Testimonials
    testimonialTitle: "प्रशंसापत्र",
    testimonialSubtitle: "डॉक्टरों और मरीजों द्वारा विश्वसनीय",
    testimonialDesc: "हेल्थएआई का उपयोग करने वाले योग्य नैदानिक विशेषज्ञों और सक्रिय रोगियों से सुनें।",
    testimonialVanceQuote: "\"हेल्थएआई ने मेरे मरीजों से जुड़ने के तरीके को बदल दिया है। स्वचालित एआई रिपोर्ट विश्लेषण मैन्युअल नैदानिक पढ़ने के घंटों बचाता है, जिससे मुझे वर्चुअल कॉल के दौरान उच्च प्रभाव वाले उपचारों पर ध्यान केंद्रित करने की अनुमति मिलती है।\"",
    testimonialVanceName: "डॉ. अलीशा वेंस, एमडी",
    testimonialVanceRole: "कार्डियोलॉजी की प्रमुख, वैनगार्ड हेल्थ",
    testimonialJenkinsQuote: "\"एआई लक्षण परीक्षक बिल्कुल अविश्वसनीय है। इसने मेरे परिवार को स्पष्ट वर्गीकरण सलाह दी जब मेरे बेटे को आधी रात को तेज बुखार था, जिससे हमें यह समझने में मदद मिली कि इंतजार करना है या आपातकालीन कक्ष में जाना है।\"",
    testimonialJenkinsName: "सराह जेनकिन्स",
    testimonialJenkinsRole: "2024 से सत्यापित प्लेटफ़ॉर्म उपयोगकर्ता",
    
    // Footer
    footerBrandDesc: "अगली पीढ़ी के नैदानिक परीक्षक, नैदानिक परामर्श पोर्टल और सुरक्षित रोगी टाइमलाइन अनुक्रमण।",
    footerFeatures: "विशेषताएं",
    footerCompliance: "अनुपालन",
    footerSupport: "सहायता",
    footerDisclaimer: "अविषयीकरण: हेल्थएआई लक्षण परीक्षक केवल सूचनात्मक उद्देश्यों के लिए नैदानिक वर्गीकरण सलाह प्रदान करता है। यह प्रमाणित चिकित्सा चिकित्सक के पेशेवर नैदानिक निर्णय, शारीरिक परीक्षा या उपचार की सिफारिश को प्रतिस्थापित नहीं करता है।",
    footerCopyright: "© 2026 हेल्थएआई इंक. सभी अधिकार सुरक्षित।",
    
    // Security Section
    secTitle: "सुरक्षा",
    secHeading: "एंटरप्राइज-ग्रेड क्लिनिकल सुरक्षा",
    secDesc: "हेल्थएआई को आधुनिक क्रिप्टोग्राफिक डेटाबेस फ्रेमवर्क पर शुरू से बनाया गया है, जो उपयोगकर्ता की गोपनीयता, सख्त एक्सेस लॉग और पूर्ण अनुपालन को प्राथमिकता देता है।",
    tagHipaa: "HIPAA अनुपालन",
    tagSoc2: "SOC2 ऑडिटेड",
    tagGdpr: "GDPR सुरक्षित",
    cardEncTitle: "एंड-टू-एंड एन्क्रिप्शन",
    cardEncDesc: "सभी संचार और अपलोड किए गए रिकॉर्ड पारगमन में और आराम से एईएस-256 मानकों का उपयोग करके एन्क्रिप्ट किए गए हैं।",
    cardAccTitle: "एक्सेस कंट्रोल",
    cardAccDesc: "विस्तृत भूमिका-आधारित सुरक्षा सेटिंग्स सुनिश्चित करती हैं कि केवल अधिकृत डॉक्टर और रोगी ही चिकित्सा फाइलों तक पहुंच सकें।",
    cardAudTitle: "ऑडिट ट्रेल्स",
    cardAudDesc: "प्रत्येक दस्तावेज़ पहुंच, परामर्श लिंक और नैदानिक क्वेरी अपरिवर्तनीय अनुपालन लॉग में दर्ज की जाती है।",
    cardApiTitle: "सुरक्षित एपीआई रूटिंग",
    cardApiDesc: "सभी बाहरी संचार मार्ग OAuth2 और हस्ताक्षरित क्रिप्टोग्राफिक JSON वेब टोकन का उपयोग करके प्रमाणित हैं।",

    // Footer Links
    footerComplianceStd: "अनुपालन आर्किटेक्चर मानक",
    footerSoc2: "SOC2 ऑडिट",
    footerKeyMgmt: "एन्क्रिप्शन कुंजी प्रबंधन",
    footerAuditRecs: "ऑडिट रिकॉर्ड",
    footerKnowledgeBase: "ज्ञानकोश (Knowledge Base)",
    footerClinicDir: "क्लिनिक निर्देशिका",
    footerContactSupport: "सहायता से संपर्क करें",
    footerFileComplaint: "शिकायत दर्ज करें",
    
    // Authentication Pages (Login, Register, OTP Verify)
    authTitle: "मानव कल्याण के लिए सटीक बुद्धिमत्ता।",
    authDesc: "एंटरप्राइज़-ग्रेड सुरक्षा के साथ अपने नैदानिक डैशबोर्ड, रोगी रिकॉर्ड और एआई-संचालित नैदानिक उपकरणों तक पहुंचें।",
    loginHeader: "स्वागत है",
    loginSubtitle: "अपने नैदानिक डैशबोर्ड तक पहुंचने के लिए साइन इन करें",
    labelEmail: "ईमेल पता",
    labelPassword: "पासवर्ड",
    labelConfirmPassword: "पासवर्ड की पुष्टि करें",
    placeholderEmail: "उदा. physician@healthai.org",
    placeholderPassword: "••••••••",
    btnSignIn: "साइन इन करें",
    btnForgot: "पासवर्ड भूल गए?",
    textNoAccount: "खाता नहीं है?",
    textHaveAccount: "पहले से ही एक खाता है?",
    linkRegister: "अभी पंजीकरण करें",
    linkLogin: "इसके बजाय लॉग इन करें",
    forgotHeader: "पासवर्ड रीसेट करें",
    forgotSubtitle: "पहुंच पुनर्प्राप्त करने के लिए अस्थायी सत्यापन कोड का अनुरोध करें",
    btnSendCode: "कोड भेजें",
    btnVerifyCode: "कोड सत्यापित करें",
    btnBackToLogin: "साइन इन पर वापस जाएं",
    otpHeader: "सत्यापन कोड दर्ज करें",
    otpSubtitle: "हमने आपके ईमेल पर 6 अंकों का सुरक्षा कोड भेजा है।",
    otpEnterMsg: "कृपया सभी 6 अंक दर्ज करें",
    btnVerify: "कोड सत्यापित करें",
    btnResendOtp: "कोड पुनः भेजें",
    registerTitle: "खाता बनाएं",
    registerSubtitle: "प्लेटफ़ॉर्म पर एक नया सुरक्षित खाता पंजीकृत करें",
    tabPatient: "रोगी प्रोफ़ाइल",
    tabDoctor: "चिकित्सा व्यवसायी",
    btnRegister: "प्रोफ़ाइल पंजीकृत करें",
    doctorRegHeadline: "नैदानिक चिकित्सक बोर्डिंग",
    doctorRegSub: "अपने लाइसेंस क्रेडेंशियल और जीपीएस समन्वय निर्दिष्ट करें।",
    doctorRegPlaceholderName: "डॉ. सराह जेनकिन्स",
    doctorRegExp: "अनुभव (वर्ष)",
    doctorRegLicense: "चिकित्सा लाइसेंस / व्यवसायी आईडी",
    doctorRegLocation: "कार्यालय / क्लिनिक स्थान कमरा",
    doctorRegAddress: "क्लिनिक का पूरा पता",
    doctorRegChooseLicense: "चिकित्सा लाइसेंस दस्तावेज चुनें (पीडीएफ/छवि)...",
    doctorRegChoosePhoto: "पेशेवर प्रोफ़ाइल फ़ोटो चुनें (छवि)...",
    doctorRegGps: "जीपीएस निर्देशांक",
    doctorRegLat: "अक्षांश",
    doctorRegLng: "रेखांश",
    doctorRegGetGps: "जीपीएस स्थान प्राप्त करें",
    doctorRegMapLoading: "नक्शा लोड हो रहा है...",
    forgotSuccessMsg: "आपके ईमेल पते पर 6 अंकों का सत्यापन कोड भेजा गया है।",
    forgotErrorMsg: "सत्यापन कोड भेजने में विफल। ईमेल पता जांचें।",
    forgotVerifyError: "अमान्य ओटीपी कोड। कृपया पुनः प्रयास करें।",
    loginErrorMsg: "लॉगिन करने में विफल। कृपया क्रेडेंशियल जांचें।",
    otpResendSuccess: "सत्यापन कोड आपके ईमेल पते पर पुनः भेज दिया गया है।",
    otpResendFailed: "सत्यापन कोड पुनः भेजने में विफल।",
    primaryFindingLabel: "मुख्य निष्कर्ष",
    severityLevelLabel: "गंभीरता का स्तर",
    clinicalRecommendationLabel: "नैदानिक सिफारिश",
    confidenceLabel: "आत्मविश्वास",
    medicineReminders: "दवा अनुस्मारक",
    medicineName: "दवा का नाम",
    dosageLabel: "खुराक",
    notifyVia: "इसके माध्यम से सूचित करें",
    contactInfoOptional: "संपर्क जानकारी (वैकल्पिक)",
    addReminder: "अनुस्मारक जोड़ें",
    noMedicineRemindersConfigured: "कोई दवा अनुस्मारक कॉन्फ़िगर नहीं किया गया है।",
    yourScheduleLog: "आपकी अनुसूची लॉग",
    inAppNotification: "इन-ऐप अधिसूचना",
    emailAlert: "ईमेल अलर्ट",
    smsAlert: "एसएमएस अलर्ट",
    recentActivity: "हाल की गतिविधि",
    allSpecialities: "सभी विशेषज्ञताएं",
    showAvailableOnly: "केवल उपलब्ध दिखाएं",
    noSpecialistsFound: "आपके फ़िल्टर मानदंडों से मेल खाने वाले कोई विशेषज्ञ नहीं मिले।",
    yearsExperience: "वर्षों का अनुभव",
    reviews: "समीक्षाएं",
    locationLabel: "स्थान",
    emailLabel: "ईमेल",
    addressLabel: "पता",
    clinicalDetailsGuidelines: "नैदानिक विवरण और दिशानिर्देश",
    available: "उपलब्ध",
    unavailable: "अनुपलब्ध",
    scheduleConsultation: "परामर्श निर्धारित करें",
    appointmentRequested: "अपॉइंटमेंट का अनुरोध किया गया!",
    appointmentScheduledSuccess: "आपकी मुलाकात सफलतापूर्वक निर्धारित हो गई है।",
    selectConsultationDate: "परामर्श तिथि चुनें",
    selectTimeSlot: "समय स्लॉट चुनें",
    noSlotsAvailable: "आज कोई स्लॉट उपलब्ध नहीं है",
    confirmBooking: "बुकिंग की पुष्टि करें",
    reviewsFor: "के लिए समीक्षाएं",
    specialist: "विशेषज्ञ",
    loadingReviews: "समीक्षाएं लोड हो रही हैं...",
    comm: "कम्यूनिकेशन",
    ethics: "नैतिकता",
    recordsSubtitle: "सुरक्षित बैकअप के साथ अपने नैदानिक रिपोर्ट और चिकित्सा फ़ाइलों को संग्रहीत, व्यवस्थित और देखें।",
    yourUploadedRecords: "आपके अपलोड किए गए रिकॉर्ड",
    noMedicalRecords: "अभी तक कोई चिकित्सा रिकॉर्ड अपलोड नहीं किया गया है।",
    uploadInstruction: "अपनी पहली रिपोर्ट अपलोड करने के लिए दाएं पैनल पर एक फ़ाइल चुनें।",
    uploadedLabel: "अपलोड किया गया",
    scanLabel: "स्कैन",
    scanning: "स्कैन किया जा रहा है...",
    verified: "सत्यापित",
    runAntiFraud: "एंटी-फ्रॉड चलाएं",
    aiInsights: "एआई अंतर्दृष्टि",
    viewFile: "फ़ाइल देखें",
    delete: "हटाएं",
    uploadDocument: "दस्तावेज़ अपलोड करें",
    selectPdfOrImage: "पीडीएफ या छवि फ़ाइल चुनें",
    maxSize: "अधिकतम आकार",
    uploadReport: "रिपोर्ट अपलोड करें",
    tarsClinicalAiInsights: "टार्स क्लिनिकल एआई अंतर्दृष्टि",
    analyzing: "विश्लेषण किया जा रहा है",
    tarsReadingReport: "टार्स आपकी रिपोर्ट पढ़ रहा है और चिकित्सा मॉडलों से परामर्श कर रहा है...",
    yoloAnalysis: "नैदानिक स्कैन योलो विश्लेषण",
    clinicalFindings: "नैदानिक निष्कर्ष और स्थितियां",
    suggestedMedications: "सुझाई गई दवाएं",
    noAnalysisData: "कोई विश्लेषण डेटा उपलब्ध नहीं है।",
    autoGenerateReminders: "अनुस्मारक स्वतः उत्पन्न करें",
    generating: "उत्पन्न किया जा रहा है...",
    done: "हो गया"
  },
  te: {
    // Nav / Sidebar
    dashboard: "డాష్‌బోర్డ్",
    workspace: "పని ప్రదేశం",
    adminPortal: "అడ్మిన్ పోర్టల్",
    appointments: "అపాయింట్‌మెంట్‌లు",
    records: "వైద్య రికార్డులు",
    chat: "చాట్ వర్క్‌స్పేస్",
    settings: "సెట్టింగ్‌లు",
    imaging: "ఇమేజింగ్ డయాగ్నోస్టిక్స్",
    logout: "లాగ్అవుట్",
    assistant: "హెల్త్AI అసిస్టెంట్",
    role: "పాత్ర",
    sosTrigger: "SOS అత్యవసర ప్రకటన",
    sosActive: "SOS అత్యవసర సక్రియం చేయబడింది!",
    sosSending: "SOS పంపుతోంది...",
    switchToAdmin: "అడ్మిన్ మోడ్‌కు మారండి",
    switchToUser: "యూజర్ మోడ్‌కు మారండి",
    switchToDoctor: "డాక్టర్ మోడ్‌కు మారండి",
    switchToCaregiver: "కేర్‌గివర్ మోడ్‌కు మారండి",
    
    // Patient Dashboard
    welcomeBack: "స్వాగతం,",
    syncRecords: "మీ వైద్య రికార్డులు మరియు అపాయింట్‌మెంట్‌లు పూర్తిగా సమకాలీకరించబడ్డాయి.",
    bookVisit: "అపాయింట్‌మెంట్ బుక్ చేయి",
    uploadRecords: "రికార్డులు అప్‌లోడ్ చేయి",
    upcomingAppts: "రాబోయే అపాయింట్‌మెంట్‌లు",
    noAppts: "రాబోయే అపాయింట్‌మెంట్‌లు ఏవీ బుక్ చేయబడలేదు.",
    findDocToBook: "బుక్ చేయడానికి వైద్యుడిని కనుగొనండి",
    cancel: "రద్దు చేయి",
    aiIntel: "AI క్లినికల్ ఇంటెలిజెన్స్",
    aiTip: "AI చిట్కా",
    recordsFolder: "వైద్య రికార్డుల ఫోల్డర్",
    recordCount: "ఫైళ్లు అప్‌లోడ్ చేయబడ్డాయి",
    noRecords: "వైద్య రికార్డులు కనుగొనబడలేదు.",
    dateLabel: "తేదీ",
    timeLabel: "సమయం",
    doctorLabel: "వైద్యుడు",
    specializationLabel: "ప్రత్యేకత",
    symptomsLabel: "లక్షణాలు",
    symptomAnalyzer: "త్వరిత లక్షణాల తనిఖీ",
    analyzeBtn: "లక్షణాలను విశ్లేషించు",
    severityLabel: "తీవ్రత",
    durationLabel: "వ్యవధి",

    // Chat Page
    searchContacts: "చాట్ చేయడానికి పరిచయాలను వెతకండి...",
    availableContacts: "అందుబాటులో ఉన్న పరిచయాలు",
    activeConvs: "సక్రియ సంభాషణలు",
    noConvs: "ఇంకా సంభాషణలు లేవు. పరిచయాలను వెతకండి!",
    selectChat: "చాట్ సంభాషణను ఎంచుకోండి",
    consultationWorkspace: "వర్క్‌స్పేస్",
    typeMessage: "సందేశాన్ని టైప్ చేయండి లేదా ఫైల్ వివరాలు రాయండి...",
    send: "పంపు",
    attachment: "అటాచ్‌మెంట్",
    
    // Doctor Dashboard
    clinicSchedule: "క్లినిక్ షెడ్యూల్",
    patientQueue: "రోగుల క్యూ",
    activeAlerts: "సక్రియ అత్యవసర హెచ్చరికలు",
    noAlerts: "ఎటువంటి అత్యవసర హెచ్చరికలు లేవు.",
    resolveAlert: "హెచ్చరిక పరిష్కరించు",
    patientName: "రోగి పేరు",
    reason: "కారణం",
    actions: "చర్యలు",
    
    // Admin Dashboard
    complaintsRegistry: "ఫిర్యాదులు & సహాయ రిజిస్ట్రీ",
    resolved: "పరిష్కరించబడింది",
    pending: "పెండింగ్",
    systemUsers: "నమోదిత సిస్టమ్ వినియోగదారులు",
    toggleStatus: "స్థితిని మార్చండి",
    active: "సక్రియం",
    inactive: "నిష్క్రియం",
    grantAdmin: "అడ్మిన్ స్విచ్ అనుమతి ఇవ్వండి",
    revokeAdmin: "అడ్మిన్ స్విచ్ అనుమతి రద్దు చేయి",
    adminAllowed: "అడ్మిన్ మోడ్ అనుమతి లభించింది",
    adminNotAllowed: "అడ్మిన్ మోడ్ అనుమతి రద్దు చేయబడింది",

    // General Layout
    loadingText: "హెల్త్AI లోడ్ అవుతోంది...",
    searchDocPlaceholder: "వైద్యుడిని పేరు లేదా ప్రత్యేకత ఆధారంగా వెతకండి...",
    uploadBtn: "మెడికల్ పిడిఎఫ్/చిత్రాన్ని అప్‌లోడ్ చేయండి",
    allRecords: "అన్ని అప్‌లోడ్ చేయబడిన వైద్య రికార్డులు",

    // Feedback System
    feedbackTitle: "సంప్రదింపుల అభిప్రాయం & సమీక్ష",
    editFeedback: "అభిప్రాయాన్ని సవరించండి",
    submitFeedback: "అభిప్రాయాన్ని సమర్పించండి",
    overallRating: "మొత్తం సంప్రదింపుల రేటింగ్",
    doctorRating: "వైద్యుడి వృత్తిపరమైన రేటింగ్",
    commentsLabel: "లిఖితపూర్వక వ్యాఖ్యలు & అనుభవ వివరాలు",
    commentsPlaceholder: "వైద్యుడు మరియు సంప్రదింపులతో మీ అనుభవం గురించి రాయండి...",
    ratingCommunication: "కమ్యూనికేషన్ శైలి",
    ratingProfessionalism: "వృత్తిపరమైన నీతి & నైపుణ్యం",
    ratingWaitTime: "వేచి ఉండే సమయం & షెడ్యూల్ కట్టుబడి ఉండడం",
    ratingSatisfaction: "మొత్తం సేవా సంప్త్యప్తి",
    optionalCategories: "వివరణాత్మక రేటింగ్‌లు (ఐచ్ఛికం)",
    privacyDisclaimer: "మీ గోప్యతను రక్షించడానికి మీ వ్యాఖ్యలు మరియు వివరణాత్మక రేటింగ్‌లు వైద్యుడు మరియు పబ్లిక్ ప్రొఫైల్‌లతో అనామకంగా భాగస్వామ్యం చేయబడతాయి.",
    feedbackSubmitted: "అభిప్రాయం విజయవంతంగా సమర్పించబడింది! మీ సమీక్షకు ధన్యవాదాలు.",
    noPendingFeedback: "అభిప్రాయం పెండింగ్‌లో ఉన్న సంప్రదింపులు ఏవీ లేవు.",
    feedbackFormError: "దయచేసి మొత్తం మరియు వైద్యుడి రేటింగ్‌లు ఎంచుకున్నారని నిర్ధారించుకోండి.",
    completeVisit: "సందర్శన పూర్తి చేయి",
    feedbackAnalytics: "అభిప్రాయ విశ్లేషణ & సమీక్షలు",
    reviewsCount: "సమీక్షలు",
    anonymousReview: "ధృవీకరించబడిన రోగి",
    averageRatingLabel: "సగటు రేటింగ్",
    viewReviewsBtn: "సమీక్షలను వీక్షించండి",
    moderateReviewsTab: "సమీక్షల నియంత్రణ",
    noReviewsMsg: "ఇంకా సమీక్షలు సమర్పించబడలేదు.",
    
    // TARS Voice Assistant
    tarsGreetingInitial: "నమస్తే! నేను TARS, మీ బహుభాషా AI అసిస్టెంట్. నేను ఇంగ్లీష్, హిందీ (हिन्दी), తెలుగు (తెలుగు), హింగ్లీష్ మరియు టింగ్లీష్ లలో మాట్లాడగలను మరియు వినగలను. ప్రారంభించడానికి \"TARS wake up\" అనండి లేదా మైక్ క్లిక్ చేయండి, లేదా అప్లికేషన్ లో నావిగేట్ చేయడానికి మీ అభ్యర్థనను టైప్ చేయండి.",
    tarsListening: "అవును, నేను వింటున్నాను.",
    tarsGoodbye: "సెలవు.",
    tarsError: "అపశ్రుతి! నాకు ఒక లోపం ఎదురైంది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    tarsLoginWarning: "నమస్తే! పూర్తి వాయిస్-ఆటోమేటెడ్ TARS సహాయం కోసం దయచేసి లాగిన్ అవ్వండి లేదా రిజిస్టర్ చేసుకోండి.",
    tarsVoiceCallWarning: "యాక్టివ్ వీడియో కాల్ సమయంలో వాయిస్ అసిస్టెంట్ నిలిపివేయబడుతుంది.",
    tarsUnsupported: "ఈ బ్రౌజర్‌లో స్పీచ్ రికగ్నిషన్ సపోర్ట్ చేయదు. దయచేసి క్రోమ్ లేదా ఎడ్జ్ ఉపయోగించండి, లేదా బ్రౌజర్ సెట్టింగ్స్‌లో మైక్రోఫోన్ అనుమతి ఇవ్వండి.",
    tarsMicDenied: "మైక్రోఫోన్ అనుమతి నిరాకరించబడింది. దయచేసి బ్రౌజర్ సెట్టింగ్స్‌లో మైక్రోఫోన్ అనుమతిని ప్రారంభించండి.",
    tarsDeactivatePhrases: "tars go to sleep,tars sleep,tars turn off,turn off tars,tars stop,stop tars,tars deactivate,tars bye,bye tars,tars paduko,tars off cheyyi,tars stop cheyyi,tars bandh cheyyi,go to sleep tars,sleep tars,oddu,bye,goodbye,silent,go silent,standby,dhanyavadalu,chalu,inkem ledhu,inkem ledu",
    tarsWakeWords: "tars,tarz,tars meluko,tars paduko,టార్స్,హే టార్స్",
    tarsClose: "TARS మూసివేయి",
    tarsThinking: "TARS ఆలోచిస్తోంది...",
    tarsListeningStatus: "TARS వింటోంది... మాట్లాడండి",
    tarsSpeakingStatus: "TARS మాట్లాడుతోంది...",
    tarsActiveStatus: "TARS వాయిస్ స్టాండ్‌బై సక్రియంగా ఉంది",
    tarsDisabledStatus: "TARS వాయిస్ స్టాండ్‌బై నిలిపివేయబడింది",
    tarsStandbyActive: "స్టాండ్‌బై: సక్రియం",
    tarsStandbyDisabled: "స్టాండ్‌బై: నిలిపివేయబడింది",
    tarsTurnOff: "ఆఫ్ చేయి",
    tarsTurnOn: "ఆన్ చేయి",
    tarsThinkingLabel: "ఆలోచిస్తోంది...",
    tarsSuggestionFindDoctor: "🔍 వైద్యుడిని కనుగొనండి",
    tarsSuggestionBookVisit: "📅 అపాయింట్‌మెంట్",
    tarsSuggestionViewRecords: "📂 రికార్డులు చూడండి",
    tarsSuggestionFileComplaint: "⚠️ ఫిర్యాదు చేయండి",
    tarsInputPlaceholder: "TARS ని ఏదైనా అడగండి...",
    tarsSuggestionFindDoctorText: "వైద్యుడిని కనుగొనండి",
    tarsSuggestionBookVisitText: "అపాయింట్మెంట్ బుక్ చేయి",
    tarsSuggestionViewRecordsText: "నా వైద్య రికార్డులు చూడండి",
    tarsSuggestionFileComplaintText: "నేను ఒక ఫిర్యాదు చేయాలనుకుంటున్నాను",
    
    // Doctor Workspace Dashboard Details
    workspaceSubtitle: "సక్రియ రోగి అత్యవసర పరిస్థితులు, రాబోయే సంప్రదింపులు మరియు క్లినికల్ రికార్డులను నిర్వహించండి.",
    totalPatients: "మొత్తం రోగులు",
    todaysVisits: "ఈరోజు సందర్శనలు",
    pendingConsults: "పెండింగ్ సంప్రదింపులు",
    averageRatingLabel: "సగటు రేటింగ్",
    patientsDirectory: "రోగుల డైరెక్టరీ",
    upcomingConsultations: "రాబోయే సంప్రదింపులు",
    urgentSurgeryReassign: "అత్యవసర శస్త్రచికిత్స: తిరిగి కేటాయించు",
    noApptsScheduled: "రాబోయే రోగి సందర్శనలు ఏవీ షెడ్యూల్ చేయబడలేదు.",
    noPatientsRegistered: "డైరెక్టరీలో రోగులు ఎవరూ నమోదు చేయబడలేదు.",
    submitLeaveRequest: "సెలవు అభ్యర్థనను సమర్పించండి",
    startDate: "ప్రారంభ తేదీ",
    endDate: "ముగింపు తేదీ",
    reasonLabel: "కారణం",
    reasonPlaceholder: "ఉదా. సమావేశానికి హాజరుకావడం, అత్యవసర వైద్య సెలవు",
    submitRequestBtn: "అభ్యర్థనను సమర్పించండి",
    leaveRequestsLog: "సెలవు అభ్యర్థనల లాగ్",
    approvedStatus: "ఆమోదించబడింది",
    pendingStatus: "పెండింగ్",
    rejectedStatus: "తిరస్కరించబడింది",
    
    // Consultation Reminders
    consultationReminders: "సంప్రదింపుల రిమైండర్‌లు",
    patientNameLabel: "సంప్రదింపులు / రోగి పేరు",
    patientNamePlaceholder: "ఉదా. రోగి: జాన్ డో",
    prepNotesLabel: "తయారీ / నోట్స్",
    prepNotesPlaceholder: "ఉదా. హృదయ రికార్డులను సమీక్షించండి",
    timeLabel: "సమయం",
    notifyViaLabel: "దీని ద్వారా తెలియజేయి",
    noConsultationRemindersConfigured: "సంప్రదింపుల రిమైండర్‌లు ఏవీ కాన్ఫిగర్ చేయబడలేదు.",
    
    // Profile Settings Page
    profileSettings: "ప్రొఫైల్ సెట్టింగ్‌లు",
    profileSettingsSubtitle: "మీ వ్యక్తిగత సెట్టింగ్‌లు, ఆరోగ్య గుణాలు మరియు సంప్రదింపు చిరునామా వివరాలను సవరించండి.",
    fullName: "పూర్తి పేరు",
    dob: "పుట్టిన తేదీ",
    gender: "లింగం",
    male: "పురుషుడు",
    female: "స్త్రీ",
    other: "ఇతర",
    heightCm: "ఎత్తు (సెం.మీ)",
    weightKg: "బరువు (కిలోలు)",
    allergies: "అలెర్జీలు",
    existingConditions: "ప్రస్తుత వైద్య పరిస్థితులు",
    homeAddress: "ఇంటి చిరునామా (అత్యవసర SOS ప్రసారానికి అవసరం)",
    doctorIdLicense: "డాక్టర్ ఐడి / లైసెన్స్ నంబర్ *",
    clinicLocationRoom: "క్లినిక్ గది స్థానం",
    specialization: "ప్రత్యేకత",
    experienceYears: "అనుభవం (సంవత్సరాలు)",
    clinicFullAddress: "క్లినిక్ పూర్తి చిరునామా",
    clinicGpsLocation: "క్లినిక్ GPS స్థానం (అత్యవసర SOS రూటింగ్ కోసం)",
    latitude: "అక్షాంశం",
    longitude: "రేఖాంశం",
    getGpsLocation: "GPS స్థానాన్ని పొందండి",
    uploadLicenseDoc: "కొత్త వైద్య లైసెన్స్ పత్రాన్ని అప్‌లోడ్ చేయండి (PDF/చిత్రం) *",
    licenseResetWarning: "కొత్త లైసెన్స్‌ను అప్‌లోడ్ చేయడం వలన మీ ఆధారాల ధృవీకరణ తిరిగి పెండింగ్‌కు మారుతుంది.",
    chooseLicense: "వైద్య లైసెన్స్‌ను ఎంచుకోండి...",
    browse: "వెతకండి",
    activeLicense: "యాక్టివ్ లైసెన్స్ పత్రం",
    currentLicense: "ప్రస్తుత",
    uploadProfilePhoto: "కొత్త ప్రొఫైల్ ఫోటోను అప్‌లోడ్ చేయండి",
    chooseProfilePhoto: "ప్రొఫైల్ ఫోటోను ఎంచుకోండి...",
    adminFullName: "అడ్మిన్ పూర్తి పేరు",
    workOfficeAddress: "పని / కార్యాలయ చిరునామా",
    saveProfile: "ప్రొఫైల్‌ను సేవ్ చేయి",
    saving: "సేవ్ అవుతోంది...",
    profileLoadFailed: "ప్రొఫైల్ సెట్టింగ్‌లను లోడ్ చేయడం విఫలమైంది.",
    profileSaveSuccess: "ప్రొఫైల్ వివరాలు విజయవంతంగా సేవ్ చేయబడ్డాయి!",
    settingsUpdateFailed: "సెట్టింగ్‌లను అప్‌డేట్ చేయడం విఫలమైంది.",
    elevatePrivileges: "ఖాతా అధికారాలను పెంచండి",
    elevateSubtitle: "అడ్మినిస్ట్రేటర్ పాత్రకు పదోన్నతి కోసం అభ్యర్థించండి. నిర్వాహకులు వినియోగదారులను నిర్వహించగలరు, ధృవీకరణ స్థితిని తనిఖీ చేయగలరు మరియు క్లినికల్ లాగ్‌లను సమీక్షించగలరు. అభ్యర్థనలు సిస్టమ్ సూపర్ అడ్మిన్ ద్వారా ఆమోదించబడాలి.",
    requestPending: "పదోన్నతి అభ్యర్థన ఆమోదం కోసం పెండింగ్‌లో ఉంది",
    requestAdminPromotion: "అడ్మిన్ పాత్ర పదోన్నతిని అభ్యర్థించండి",
    promotionRequestSuccess: "పదోన్నతి అభ్యర్థన విజయవంతంగా పంపబడింది!",
    promotionRequestFailed: "పదోన్నతి అభ్యర్థనను సమర్పించడం విఫలమైంది.",
    themePersonalization: "థీమ్ & వ్యక్తిగతీకరణ",
    themeSubtitle: "మీకు ఇష్టమైన ఇంటర్‌ఫేస్ రంగుల ప్యానెట్‌ను ఎంచుకోండి. ఈ సెట్టింగ్‌లు డాక్టర్, రోగి మరియు పరిపాలన స్థలాలలో ప్రపంచవ్యాప్తంగా వర్తిస్తాయి.",
    brandPrimaryColor: "బ్రాండ్ ప్రాథమిక రంగు",
    secondaryAccentColor: "ద్వితీయ యాక్సెంట్ రంగు",
    portalBgColor: "పోర్టల్ నేపథ్య రంగు",
    dashboardSurfaceColor: "డాష్‌బోర్డ్ ఉపరితల రంగు",
    livePalettePreview: "Live Palette Preview", // keep "Live Palette Preview" as is or transliterated
    sampleDashboardElement: "నమూనా డాష్‌బోర్డ్ మూలకం",
    sampleDashboardDesc: "ఉత్పన్నమైన కంటైనర్ స్టైలింగ్ మరియు చదవగలిగే వచన ఓవర్‌లేలు మీ ఎంపికకు అనుగుణంగా డైనమిక్‌గా సర్దుబాటు చేయబడతాయి.",
    sampleButton: "నమూనా బటన్",
    applyCustomTheme: "అనుకూల థీమ్ సెట్టింగ్‌లను వర్తింపజేయి",
    
    // Theme options
    classicBlue: "క్లాసిక్ బ్లూ",
    classicBlueDesc: "ప్రశాంతమైన ప్రొఫెషనల్ బ్లూ",
    midnightNavy: "మిడ్‌నైట్ నేవీ",
    midnightNavyDesc: "తక్కువ వెలుతురు డార్క్ మోడ్",
    forestTeal: "ఫారెస్ట్ టీల్",
    forestTealDesc: "తాజా క్లినికల్ మింట్",
    royalViolet: "రాయల్ వైలెట్",
    royalVioletDesc: "సృజనాత్మక యాక్సెంట్ వైలెట్",
    warmRose: "వార్మ్ రోజ్",
    warmRoseDesc: "వెచ్చని సౌకర్యవంతమైన రోజ్",
    customStudio: "కస్టమ్ స్టూడియో",
    customStudioDesc: "మీ స్వంత థీమ్ ప్యానెట్‌ను డిజైన్ చేయండి",
    
    // Doctor Specializations
    "Cardiology": "కార్డియాలజీ",
    "Dermatology": "డెర్మటాలజీ",
    "General Medicine": "జనరల్ మెడిసిన్",
    "Neurology": "న్యూరాలజీ",
    "Pediatrics": "పీడియాట్రిక్స్",
    
    // Landing / Hero Elements
    trustBadge: "నెక్స్ట్-జెన్ మెడికల్ ఇంటెలిజెన్స్",
    heroTitle: "AI తో పునర్నిర్మించబడిన ఆరోగ్య సంరక్షణ",
    heroSubtext: "వైద్యులతో కనెక్ట్ అవ్వండి, డయాగ్నోస్టిక్స్ నివేదికలను విశ్లేషించండి, లక్షణాలను తక్షణమే తనిఖీ చేయండి మరియు వైద్య రికార్డులను ఒక తెలివైన, HIPAA-కంప్లైంట్ రోగి డాష్‌బోర్డ్ ద్వారా నిర్వహించండి.",
    btnGetStarted: "ఉచితంగా ప్రారంభించండి",
    btnExploreFeatures: "ఫీచర్లను అన్వేషించండి",
    
    // Mockup Card Translations
    mockupHeartRate: "లైవ్ హార్ట్ రేట్",
    mockupHealthIndex: "హెల్త్ ఇండెక్స్",
    mockupVitalsStatus: "వైటల్స్ స్థిరంగా ఉన్నాయి. కార్యాచరణ స్థాయిలు ఉత్తమంగా ఉన్నాయి. ఈ వారం నిద్ర నాణ్యత 8% పెరిగింది.",
    mockupReportDissection: "AI నివేదిక విశ్లేషణ",
    mockupAnalysisDesc: "క్లినికల్ విశ్లేషణ: CBC నివేదిక తేలికపాటి ఇనుము లోపం రక్తహీనతను చూపుతుంది (Hb: 10.8 g/dL). నిద్రకు అంతరాయం ఏర్పడింది. ఇనుము అధికంగా ఉండే ఆహారం & వర్చువల్ తనిఖీని షెడ్యూల్ చేయాలని సిఫార్సు చేయబడింది.",
    mockupHbLabel: "Hb: 10.8 g/dL (తక్కువ)",
    mockupFerritinLabel: "ఫెర్రిటిన్: 12 ng/mL",
    mockupActionReq: "చర్య అవసరం",
    mockupConnected: "కనెక్ట్ చేయబడింది",
    
    // Landing Core Features
    landingCapabilities: "సామర్థ్యాలు",
    landingIntelligentHealth: "ఇంటెలిజెంట్ హెల్త్ సర్వీసెస్",
    landingServicesSubtitle: "డయాగ్నోస్టిక్ ట్రయాగింగ్, క్లినికల్ కమ్యూనికేషన్స్ మరియు రోజువారీ వైద్య లాగ్‌లను క్రమబద్ధీకరించడానికి రూపొందించబడిన ఏకీకృత ప్లాట్‌ఫారమ్‌ను కనుగొనండి.",
    featureTriage: "ట్రయాజ్",
    featureTriageTitle: "AI లక్షణాల తనిఖీ",
    featureTriageDesc: "సురక్షితమైన వైద్య AI ద్వారా ఆధారితమైన సంభావ్య కారణాల జాబితాతో లక్షణాలను విశ్లేషించండి మరియు తక్షణ, వ్యక్తిగతీకరించిన ట్రయాజ్ సలహాలను పొందండి.",
    featureTelemed: "టెలిమెడిసిన్",
    featureTelemedTitle: "వర్చువల్ సంప్రదింపులు",
    featureTelemedDesc: "తక్కువ-లేటెన్సీ, HIPAA-అనుకూలమైన వీడియో కాల్‌లు మరియు ప్రైవేట్ చాట్ సెషన్‌ల ద్వారా ధృవీకరించబడిన ఆరోగ్య నిపుణులతో నేరుగా సంప్రదించండి.",
    featureRxSafety: "Rx సేఫ్టీ",
    featureRxSafetyTitle: "మందుల నిర్వహణ",
    featureRxSafetyDesc: "స్మార్ట్ పిల్ రిమైండర్‌లను సెట్ చేయండి, మోతాదు చరిత్రను ట్రాక్ చేయండి మరియు డ్రగ్-టు-డ్రగ్ పరస్పర చర్యల కోసం స్వయంచాలక హెచ్చరికలను పొందండి.",
    featureDiag: "డయాగ్నోస్టిక్స్",
    featureDiagTitle: "నివేదిక విశ్లేషణ",
    featureDiagDesc: "వైద్య పదజాలం యొక్క సరళమైన భాషా సారాంశాలను స్వీకరించడానికి సంక్లిష్టమైన ల్యాబ్ నివేదికలను లేదా పరీక్ష పత్రాలను తక్షణమే విశ్లేషించండి.",
    featureVitals: "వైటల్స్ సమకాలీకరణ",
    featureVitalsTitle: "ఆరోగ్య పర్యవేక్షణ",
    featureVitalsDesc: "హార్ట్ రేట్లు, స్టెప్ లాగ్‌లు, బ్లడ్ ఆక్సిజన్ స్థాయిలు మరియు వారపు నిద్ర విశ్లేషణలతో సహా ధరించగలిగే ఆరోగ్య డేటాను సమకాలీకరించండి మరియు track చేయండి.",
    featureEmergency: "24/7 సంరక్షణ",
    featureEmergencyTitle: "అత్యవసర మార్గదర్శకత్వం",
    featureEmergencyDesc: "అత్యవసర ప్రోటోకాల్‌లు, ప్రథమ చికిత్స ఆదేశాలకు తక్షణ ప్రాప్యత మరియు సమీప ఆసుపత్రి సదుపాయానికి తక్షణ మార్గం.",
    learnMore: "ఇంకా తెలుసుకోండి",
    
    // Landing Stats
    statCheckerAccuracyVal: "99.4%",
    statCheckerAccuracyLbl: "AI తనిఖీ ఖచ్చితత్వం",
    statConsultationsVal: "150k+",
    statConsultationsLbl: "సంప్రదింపులు",
    statResponseVal: "<2 నిమిషాలు",
    statResponseLbl: "సగటు ప్రతిస్పందన",
    statArchitectureVal: "HIPAA",
    statArchitectureLbl: "కంప్లైంట్ ఆర్కిటెక్చర్",
    
    // Sliding Text Section
    slidingLine1: "వైద్యుల కోసం నిర్మించబడింది.",
    slidingLine2: "రోగుల కోసం రూపొందించబడింది.",
    slidingLine3: "AI చేత నడపబడుతుంది.",
    
    // Testimonials
    testimonialTitle: "ధృవపత్రాలు",
    testimonialSubtitle: "వైద్యులు & రోగుల నమ్మకం",
    testimonialDesc: "HealthAI ని ఉపయోగిస్తున్న అర్హత కలిగిన క్లినికల్ నిపుణులు మరియు క్రియాశీల రోగుల నుండి వినండి.",
    testimonialVanceQuote: "\"హెల్త్AI నా రోగులతో నేను కనెక్ట్ అయ్యే విధానాన్ని మార్చివేసింది. స్వయంచాలక AI రిపోర్ట్ విశ్లేషణ గంటల తరబడి మాన్యువల్ డయాగ్నోస్టిక్ పఠనాన్ని ఆదా చేస్తుంది, వర్చువల్ కాల్‌ల సమయంలో అధిక-ప్రభావ చికిత్సలపై దృష్టి పెట్టడానికి నన్ను అనుమతిస్తుంది.\"",
    testimonialVanceName: "డాక్టర్ అలిషా వాన్స్, MD",
    testimonialVanceRole: "చీఫ్ ఆఫ్ కార్డియాలజీ, వాన్‌గార్డ్ హెల్త్",
    testimonialJenkinsQuote: "\"AI లక్షణాల తనిఖీ నిజంగా అద్భుతమైనది. అర్ధరాత్రి మా అబ్బాయికి విపరీతమైన జ్వరం వచ్చినప్పుడు మా కుటుంబానికి స్పష్టమైన ట్రయాజ్ సలహాను ఇచ్చింది, మేము వేచి ఉండాలా లేదా అత్యవసర గదికి వెళ్ళాలా అనేది అర్థం చేసుకోవడానికి సహాయపడింది.\"",
    testimonialJenkinsName: "సారా జెంకిన్స్",
    testimonialJenkinsRole: "2024 నుండి ధృవీకరించబడిన ప్లాట్‌ఫారమ్ వినియోగదారు",
    
    // Footer
    footerBrandDesc: "తదుపరి తరం డయాగ్నోస్టిక్ చెకర్స్, క్లినికల్ కన్సల్టేషన్ పోర్టల్‌లు మరియు సురక్షితమైన రోగి టైమ్‌లైన్ ఇండెక్సింగ్.",
    footerFeatures: "ఫీచర్లు",
    footerCompliance: "సమ్మతి",
    footerSupport: "మద్దతు",
    footerDisclaimer: "నిరాకరణ: హెల్త్AI లక్షణాల తనిఖీ సమాచార ప్రయోజనాల కోసం మాత్రమే డయాగ్నోస్టిక్ ట్రయాగింగ్ సలహాలను అందిస్తుంది. ఇది ధృవీకరించబడిన వైద్యుడి వృత్తిపరమైన క్లినికల్ తీర్పు, శారీరక పరీక్ష లేదా చికిత్స సిఫార్సును భర్తీ చేయదు.",
    footerCopyright: "© 2026 హెల్త్AI ఇంక్. అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.",
    
    // Security Section
    secTitle: "భద్రత",
    secHeading: "ఎంటర్‌ప్రైజ్-గ్రేడ్ క్లినికల్ సెక్యూరిటీ",
    secDesc: "HealthAI అనేది ఆధునిక క్రిప్టోగ్రాఫిక్ డేటాబేస్ ఫ్రేమ్‌వర్క్‌లపై మొదటి నుండి నిర్మించబడింది, వినియోగదారు గోప్యత, కఠినమైన యాక్సెస్ లాగ్‌లు మరియు పూర్తి సమ్మతికి ప్రాధాన్యత ఇస్తుంది.",
    tagHipaa: "HIPAA కంప్లైంట్",
    tagSoc2: "SOC2 ఆడిట్ చేయబడింది",
    tagGdpr: "GDPR రక్షించబడింది",
    cardEncTitle: "ఎండ్-టు-ఎండ్ ఎన్‌క్రిప్షన్",
    cardEncDesc: "AES-256 ప్రమాణాలను ఉపయోగించి రవాణాలో మరియు నిల్వలో అన్ని కమ్యూనికేషన్‌లు మరియు అప్‌లోడ్ చేసిన రికార్డులు ఎన్‌క్రిప్ట్ చేయబడతాయి.",
    cardAccTitle: "యాక్సెస్ కంట్రోల్",
    cardAccDesc: "వివరణాత్మక పాత్ర-ఆధారిత భద్రతా సెట్టింగ్‌లు కేవలం అధీకృత వైద్యులు మరియు రోగులు మాత్రమే వైద్య ఫైల్‌లను యాక్సెస్ చేయగలరని నిర్ధారిస్తాయి.",
    cardAudTitle: "ఆడిట్ ట్రైల్స్",
    cardAudDesc: "ప్రతి డాక్యుమెంట్ యాక్సెస్, సంప్రదింపు లింక్ మరియు డయాగ్నోస్టిక్ ప్రశ్న మార్చలేని సమ్మతి లాగ్‌లలో నమోదు చేయబడతాయి.",
    cardApiTitle: "సురక్షితమైన API రూటింగ్",
    cardApiDesc: "అన్ని బాహ్య కమ్యూనికేషన్ మార్గాలు OAuth2 మరియు సంతకం చేయబడిన క్రిప్టోగ్రాఫిక్ JSON వెబ్ టోకెన్‌లను ఉపయోగించి ప్రామాణీకరించబడతాయి.",

    // Footer Links
    footerComplianceStd: "కంప్లైంట్ ఆర్కిటెక్చర్ ప్రమాణాలు",
    footerSoc2: "SOC2 ఆడిట్‌లు",
    footerKeyMgmt: "ఎన్‌క్రిప్షన్ కీ మేనేజ్‌మెంట్",
    footerAuditRecs: "ఆడిట్ రికార్డులు",
    footerKnowledgeBase: "నాలెడ్జ్ బేస్",
    footerClinicDir: "క్లినికల్ డైరెక్టరీ",
    footerContactSupport: "మద్దతును సంప్రదించండి",
    footerFileComplaint: "ఫిర్యాదు దాఖలు చేయండి",
    
    // Authentication Pages (Login, Register, OTP Verify)
    authTitle: "మానవ శ్రేయస్సు కోసం ఖచ్చితమైన మేధస్సు.",
    authDesc: "ఎంటర్‌ప్రైజ్-గ్రేడ్ భద్రతతో మీ క్లినికల్ డాష్‌బోర్డ్, రోగి రికార్డులు మరియు AI-ఆధారిత రోగనిర్ధారణ సాధనాలను యాక్సెస్ చేయండి.",
    loginHeader: "తిరిగి స్వాగతం",
    loginSubtitle: "మీ క్లినికల్ డాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి సైన్ ఇన్ చేయండి",
    labelEmail: "ఇమెయిల్ చిరునామా",
    labelPassword: "పాస్‌వర్డ్",
    labelConfirmPassword: "పాస్‌వర్డ్‌ను నిర్ధారించండి",
    placeholderEmail: "ఉదా. physician@healthai.org",
    placeholderPassword: "••••••••",
    btnSignIn: "సైన్ ఇన్ చేయి",
    btnForgot: "పాస్‌వర్డ్ మర్చిపోయారా?",
    textNoAccount: "ఖాతా లేదా?",
    textHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    linkRegister: "ఇప్పుడే నమోదు చేసుకోండి",
    linkLogin: "బదులుగా లాగిన్ అవ్వండి",
    forgotHeader: "పాస్‌వర్డ్ రీసెట్",
    forgotSubtitle: "యాక్సెస్‌ను పునరుద్ధరించడానికి తాత్కాలిక ధృవీకరణ కోడ్‌ను అభ్యర్థించండి",
    btnSendCode: "కోడ్ పంపు",
    btnVerifyCode: "కోడ్‌ను ధృవీకరించు",
    btnBackToLogin: "సైన్ ఇన్‌కు తిరిగి వెళ్లు",
    otpHeader: "ధృవీకరణ కోడ్‌ను నమోదు చేయండి",
    otpSubtitle: "మేము మీ ఇమెయిల్‌కు 6-అంకెల భద్రతా కోడ్‌ను పంపాము.",
    otpEnterMsg: "దయచేసి మొత్తం 6 అంకెలను నమోదు చేయండి",
    btnVerify: "కోడ్‌ను ధృవీకరించు",
    btnResendOtp: "కోడ్‌ను మళ్లీ పంపు",
    registerTitle: "ఖాతాను సృష్టించండి",
    registerSubtitle: "ప్లాట్‌ఫారమ్‌లో కొత్త సురక్షిత ఖాతాను నమోదు చేయండి",
    tabPatient: "రోగి ప్రొఫైల్",
    tabDoctor: "మెడికల్ ప్రాక్టీషనర్",
    btnRegister: "ప్రొఫైల్ నమోదు చేయి",
    doctorRegHeadline: "క్లినికల్ ప్రాక్టీషనర్ బోర్డింగ్",
    doctorRegSub: "మీ లైసెన్స్ ఆధారాలు మరియు GPS సమన్వయాన్ని పేర్కొనండి.",
    doctorRegPlaceholderName: "డాక్టర్ సారా జెంకిన్స్",
    doctorRegExp: "అనుభవం (సంవత్సరాలు)",
    doctorRegLicense: "వైద్య లైసెన్స్ / ప్రాక్టీషనర్ ID",
    doctorRegLocation: "ఆఫీస్ / క్లినిక్ లొకేషన్ రూమ్",
    doctorRegAddress: "క్లినిక్ పూర్తి చిరునామా",
    doctorRegChooseLicense: "వైద్య లైసెన్స్ పత్రాన్ని ఎంచుకోండి (PDF/చిత్రం)...",
    doctorRegChoosePhoto: "వృత్తిపరమైన ప్రొఫైల్ ఫోటోను ఎంచుకోండి (చిత్రం)...",
    doctorRegGps: "GPS కోఆర్డినేట్లు",
    doctorRegLat: "అక్షాంశం",
    doctorRegLng: "రేఖాంశం",
    doctorRegGetGps: "GPS స్థానాన్ని పొందండి",
    doctorRegMapLoading: "మ్యాప్ లోడ్ అవుతోంది...",
    forgotSuccessMsg: "మీ ఇమెయిల్ చిరునామాకు 6-అంకెల ధృవీకరణ కోడ్ పంపబడింది.",
    forgotErrorMsg: "ధృవీకరణ కోడ్ పంపడం విఫలమైంది. ఇమెయిల్ చిరునామాను తనిఖీ చేయండి.",
    forgotVerifyError: "చెల్లని OTP కోడ్. దయచేసి మళ్లీ ప్రయత్నించండి.",
    loginErrorMsg: "లాగిన్ విఫలమైంది. దయచేసి ఆధారాలను తనిఖీ చేయండి.",
    otpResendSuccess: "మీ ఇమెయిల్ చిరునామాకు ధృవీకరణ కోడ్ మళ్లీ పంపబడింది.",
    otpResendFailed: "ధృవీకరణ కోడ్ మళ్లీ పంపడం విఫలమైంది.",
    primaryFindingLabel: "ముఖ్యమైన ఫలితం",
    severityLevelLabel: "తీవ్రత స్థాయి",
    clinicalRecommendationLabel: "వైద్య రికమండేషన్",
    confidenceLabel: "విశ్వసనీయత",
    medicineReminders: "మందుల రిమైండర్లు",
    medicineName: "మందు పేరు",
    dosageLabel: "మోతాదు",
    notifyVia: "దీని ద్వారా తెలియజేయండి",
    contactInfoOptional: "సంప్రదింపు సమాచారం (ఐచ్ఛికం)",
    addReminder: "రిమైండర్ జోడించు",
    noMedicineRemindersConfigured: "మందుల రిమైండర్లు ఏవీ కాన్ఫిగర్ చేయబడలేదు.",
    yourScheduleLog: "మీ షెడ్యూల్ లాగ్",
    inAppNotification: "ఇన్-యాప్ నోటిఫికేషన్",
    emailAlert: "ఇమెయిల్ హెచ్చరిక",
    smsAlert: "SMS హెచ్చరిక",
    recentActivity: "ఇటీవలి కార్యాచరణ",
    allSpecialities: "అన్ని ప్రత్యేకతలు",
    showAvailableOnly: "అందుబాటులో ఉన్నవి మాత్రమే చూపించు",
    noSpecialistsFound: "మీ ఫిల్టర్ ప్రమాణాలకు సరిపోయే నిపుణులు ఎవరూ కనుగొనబడలేదు.",
    yearsExperience: "సంవత్సరాల అనుభవం",
    reviews: "సమీక్షలు",
    locationLabel: "స్థానం",
    emailLabel: "ఇమెయిల్",
    addressLabel: "చిరునామా",
    clinicalDetailsGuidelines: "క్లినికల్ వివరాలు & మార్గదర్శకాలు",
    available: "అందుబాటులో ఉంది",
    unavailable: "అందుబాటులో లేదు",
    scheduleConsultation: "సంప్రదింపులను షెడ్యూల్ చేయి",
    appointmentRequested: "అపాయింట్‌మెంట్ అభ్యర్థించబడింది!",
    appointmentScheduledSuccess: "మీ సందర్శన విజయవంతంగా షెడ్యూల్ చేయబడింది.",
    selectConsultationDate: "సంప్రదింపు తేదీని ఎంచుకోండి",
    selectTimeSlot: "సమయ స్లాట్‌ను ఎంచుకోండి",
    noSlotsAvailable: "ఈ రోజుకు స్లాట్లు అందుబాటులో లేవు",
    confirmBooking: "బుకింగ్ నిర్ధారించు",
    reviewsFor: "సమీక్షలు",
    specialist: "నిపుణుడు",
    loadingReviews: "సమీక్షలను లోడ్ చేస్తోంది...",
    comm: "కమ్యూనికేషన్",
    ethics: "నీతి",
    recordsSubtitle: "సురక్షితమైన బ్యాకప్‌తో మీ రోగనిర్ధారణ నివేదికలను మరియు వైద్య ఫైల్‌లను నిల్వ చేయండి, నిర్వహించండి మరియు వీక్షించండి.",
    yourUploadedRecords: "మీరు అప్‌లోడ్ చేసిన రికార్డులు",
    noMedicalRecords: "వైద్య రికార్డులు ఏవీ ఇంకా అప్‌లోడ్ చేయబడలేదు.",
    uploadInstruction: "మీ మొదటి నివేదికను అప్‌లోడ్ చేయడానికి కుడి వైపు ప్యానెల్‌లో ఒక ఫైల్‌ను ఎంచుకోండి.",
    uploadedLabel: "అప్‌లోడ్ చేయబడింది",
    scanLabel: "స్కాన్",
    scanning: "స్కాన్ చేస్తోంది...",
    verified: "ధృవీకరించబడింది",
    runAntiFraud: "యాంటీ-ఫ్రాడ్ రన్ చేయి",
    aiInsights: "AI అంతర్దృష్టులు",
    viewFile: "ఫైల్ చూడండి",
    delete: "తొలగించు",
    uploadDocument: "పత్రాన్ని అప్‌లోడ్ చేయి",
    selectPdfOrImage: "PDF లేదా ఇమేజ్ ఫైల్‌ను ఎంచుకోండి",
    maxSize: "గరిష్ట పరిమాణం",
    uploadReport: "నివేదికను అప్‌లోడ్ చేయి",
    tarsClinicalAiInsights: "TARS క్లినికల్ AI అంతర్దృష్టులు",
    analyzing: "విశ్లేషిస్తోంది",
    tarsReadingReport: "TARS మీ నివేదికను చదువుతోంది మరియు వైద్య నమూనాలను సంప్రదిస్తోంది...",
    yoloAnalysis: "డయాగ్నోస్టిక్ స్కాన్ YOLO విశ్లేషణ",
    clinicalFindings: "క్లినికల్ ఫలితాలు & పరిస్థితులు",
    suggestedMedications: "సూచించబడిన మందులు",
    noAnalysisData: "విశ్లేషణ డేటా అందుబాటులో లేదు.",
    autoGenerateReminders: "రిమైండర్లను ఆటోమేటిక్‌గా సృష్టించు",
    generating: "సృష్టిస్తోంది...",
    done: "పూర్తయింది"
  }
};

const nameTranslations = {
  hi: {
    "sarah johnson": "सराह जॉनसन",
    "sarah jenkins": "सराह जेनकिन्स",
    "john doe": "जॉन डो",
    "harrington": "हैरिंगटन",
    "harika dantula": "हरिका दंतुला",
    "sricharan pranav": "श्रीचरण प्रणव",
    "pranav": "प्रणव",
    "alice smith": "एलिस स्मिथ",
    "bob johnson": "बॉब जॉनसन",
    "charlie brown": "चार्ली ब्राउन",
    "diana prince": "डायना प्रिंस",
    "evan wright": "एवन राइट",
    "urgent medical leave": "आपातकालीन चिकित्सा अवकाश",
    "family issues": "पारिवारिक मुद्दे",
    "urgent surgery: reassign": "आपातकालीन सर्जरी: पुनः सौंपें",
    "no upcoming patient visits scheduled.": "कोई आगामी रोगी नियुक्तियाँ निर्धारित हैं।",
    "no consultation reminders configured.": "कोई परामर्श अनुस्मारक कॉन्फ़िगर नहीं किया गया है।",
    "contact dermatitis / eczema": "संपर्क जिल्द की सूजन / एक्जिमा (Contact Dermatitis / Eczema)",
    "acute pharyngitis": "तीव्र ग्रसनीशोथ (Acute Pharyngitis)",
    "normal chest radiograph": "सामान्य छाती का एक्स-रे (Normal Chest Radiograph)",
    "normal scan": "सामान्य स्कैन (Normal Scan)",
    "eczema": "एक्जिमा",
    "normal throat": "सामान्य गला",
    "throat redness": "गले की लालिमा",
    "visual inspection indicates localized dermatological lesions. moderate epidermal erythema and hyperpigmented borders are observed. the lesion displays distinct asymmetrical margins and minor scaling. recommend differential diagnosis for contact dermatitis, eczema, or localized fungal infection. patient advised to avoid scratching and apply soothing emollient (such as calamine lotion or mild hydrocortisone 1% cream topically twice daily as needed).": "दृश्य निरीक्षण स्थानीयकृत त्वचा संबंधी घावों को दर्शाता है। मध्यम बाह्यत्वचा एरिथेमा और हाइपरपिग्मेंटेड बॉर्डर देखे जाते हैं। घाव स्पष्ट असममित मार्जिन और मामूली स्केलिंग प्रदर्शित करता है। संपर्क जिल्द की सूजन, एक्जिमा, या स्थानीयकृत फंगल संक्रमण के लिए अंतर निदान की सिफारिश की जाती है। रोगी को खुजली से बचने और सुखदायक कम करने वाले (जैसे कैलामाइन लोशन या हल्के हाइड्रोकार्टिसोन 1% क्रीम को जरूरत के अनुसार दिन में दो बार शीर्ष पर लगाने) की सलाह दी जाती है।",
    "posterior pharyngeal wall shows significant vascular congestion and diffuse erythema. tonsillar swelling is mild (grade 1) with no visible purulent exudate or cobblestoning. slight uvular inflammation noted. findings are highly consistent with acute viral pharyngitis. recommend warm saline rinses, adequate hydration, and symptomatic monitoring. suggested otc medicines: throat lozenges every 4 hours for irritation, and paracetamol (500mg up to 3 times daily as needed) for mild soreness.": "पीछे की ग्रसनी दीवार महत्वपूर्ण संवहनी जमाव और विसरित लालिमा दिखाती है। टॉन्सिलर सूजन हल्की (ग्रेड 1) है जिसमें कोई दृश्यमान मवाद या कोबलेस्टोनिंग नहीं है। यूवुला में हल्की सूजन देखी गई। निष्कर्ष तीव्र वायरल ग्रसनीशोथ के साथ अत्यधिक सुसंगत हैं। गर्म खारे पानी से कुल्ला करने, पर्याप्त जलयोजन और रोगसूचक निगरानी की सिफारिश की जाती है। सुझाई गई ओटीसी दवाएं: जलन के लिए हर 4 घंटे में गले की गोलियां, और हल्के दर्द के लिए पैरासिटामोल (500 मिलीग्राम आवश्यकतानुसार दैनिक 3 बार तक)।",
    "chest/skeletal radiograph analyzed. lungs demonstrate clear aeration bilateral. no consolidation, pleural effusion, or active airspace disease detected. cardiomediastinal silhouette and hila are within normal limits. skeletal structures show normal alignment with no obvious signs of acute fracture or subluxation. findings suggest normal respiratory and osseous structures. no prescription medications required. maintain normal health monitoring.": "छाती/कंकाल रेडियोग्राफ का विश्लेषण किया गया। फेफड़े दोनों तरफ स्पष्ट वातन प्रदर्शित करते हैं। कोई संपीड़न, फुफ्फुस प्रवाह, या सक्रिय वायुमार्ग रोग नहीं पाया गया। कार्डियोमीडियास्टिनल सिल्हूट और हिला सामान्य सीमा के भीतर हैं। कंकाल संरचनाएं सामान्य संरेखण दिखाती हैं जिसमें तीव्र फ्रैक्चर या सब्लक्सेशन का कोई स्पष्ट संकेत नहीं है। निष्कर्ष सामान्य श्वसन और अस्थि संरचनाओं का सुझाव देते हैं। किसी प्रिस्क्रिप्शन दवा की आवश्यकता नहीं है। सामान्य स्वास्थ्य निगरानी बनाए रखें।",
    "preliminary clinical imaging scan processed. general structural integrity of the target region appears unremarkable, with no clear anomalies or acute pathology visible. further specific diagnostic examinations may be required if clinical symptoms persist. mild symptoms may be managed with standard over-the-counter pain relievers or topical emollients as appropriate.": "प्रारंभिक नैदानिक इमेजिंग स्कैन संसाधित किया गया। लक्षित क्षेत्र की सामान्य संरचनात्मक अखंडता सामान्य प्रतीत होती है, जिसमें कोई स्पष्ट विसंगति या तीव्र विकृति दिखाई नहीं दे रही है। यदि नैदानिक लक्षण बने रहते हैं तो आगे विशिष्ट नैदानिक परीक्षाओं की आवश्यकता हो सकती है। हल्के लक्षणों को आवश्यकतानुसार मानक ओवर-द-काउंटर दर्द निवारक या सामयिक मलहम के साथ प्रबंधित किया जा सकता है।",
    "apply soothing calamine lotion or mild hydrocortisone 1% cream topically twice daily as needed. avoid scratching.": "ज़रूरत के अनुसार दिन में दो बार सुखदायक कैलामाइन लोशन या हल्की हाइड्रोकार्टिसोन 1% क्रीम शीर्ष पर लगाएं। खुजली से बचें।",
    "warm saline gargles, throat lozenges every 4 hours, and paracetamol 500mg up to 3 times daily as needed.": "गर्म खारे पानी के गरारे, हर 4 घंटे में गले की गोलियां, और आवश्यकतानुसार दिन में 3 बार तक पैरासिटामोल 500 मिलीग्राम।",
    "no active airspace disease or fracture detected. maintain routine health checks.": "कोई सक्रिय वायुमार्ग रोग या फ्रैक्चर नहीं पाया गया। नियमित स्वास्थ्य जांच बनाए रखें।",
    "no acute pathology visible. follow up if symptoms persist.": "कोई तीव्र विकृति दिखाई नहीं दे रही है। यदि लक्षण बने रहते हैं तो अनुवर्ती कार्रवाई करें।",
    "standard clinical disclaimer: this ai-generated report is for informational purposes only. it does not replace professional medical advice, diagnosis, or treatment. please consult a qualified healthcare provider before starting any new medication or treatment plan.": "मानक नैदानिक अस्वीकरण: यह एआई-जनित रिपोर्ट केवल सूचनात्मक उद्देश्यों के लिए है। यह पेशेवर चिकित्सा सलाह, निदान या उपचार को प्रतिस्थापित नहीं करती है। कृपया कोई भी नई दवा या उपचार योजना शुरू करने से पहले एक योग्य स्वास्थ्य सेवा प्रदाता से परामर्श लें।",
    "welcome": "स्वागत",
    "account initialized. no appointments booked yet.": "खाता प्रारंभ किया गया। अभी तक कोई अपॉइंटमेंट बुक नहीं किया गया है।"
  },
  te: {
    "sarah johnson": "సారా జాన్సన్",
    "sarah jenkins": "సారా జెంకిన్స్",
    "john doe": "జాన్ డో",
    "harrington": "హారింగ్టన్",
    "harika dantula": "హరికా దంతుల",
    "sricharan pranav": "శ్రీచరణ్ ప్రణవ్",
    "pranav": "ప్రణవ్",
    "alice smith": "ఆలిస్ స్మిత్",
    "bob johnson": "బాబ్ జాన్సన్",
    "charlie brown": "చార్లీ బ్రౌన్",
    "diana prince": "డయానా ప్రిన్స్",
    "evan wright": "ఇవాన్ రైట్",
    "urgent medical leave": "అత్యవసర వైద్య సెలవు",
    "family issues": "కుటుంబ సమస్యలు",
    "urgent surgery: reassign": "అత్యవసర శస్త్రచికిత్స: తిరిగి కేటాయించు",
    "no upcoming patient visits scheduled.": "రాబోయే రోగి సందర్శనలు ఏవీ షెడ్యూల్ చేయబడలేదు.",
    "no consultation reminders configured.": "సంప్రదింపుల రిమైండర్‌లు ఏవీ కాన్గర్ చేయబడలేదు.",
    "contact dermatitis / eczema": "కాంటాక్ట్ డెర్మటైటిస్ / తామర (Eczema)",
    "acute pharyngitis": "తీవ్రమైన ఫారింజైటిస్ (Acute Pharyngitis)",
    "normal chest radiograph": "సాధారణ ఛాతీ ఎక్స్-రే (Normal Chest Radiograph)",
    "normal scan": "సాధారణ స్కాన్ (Normal Scan)",
    "eczema": "తామర (Eczema)",
    "normal throat": "సాధారణ గొంతు",
    "throat redness": "గొంతు ఎరుపు",
    "visual inspection indicates localized dermatological lesions. moderate epidermal erythema and hyperpigmented borders are observed. the lesion displays distinct asymmetrical margins and minor scaling. recommend differential diagnosis for contact dermatitis, eczema, or localized fungal infection. patient advised to avoid scratching and apply soothing emollient (such as calamine lotion or mild hydrocortisone 1% cream topically twice daily as needed).": "దృశ్య తనిఖీ స్థానికీకరించిన చర్మ సంబంధిత గాయాలను సూచిస్తుంది. మితమైన ఎపిడెర్మల్ ఎరిథీమా మరియు హైపర్‌పిగ్మెంటెడ్ అంచులు గమనించబడ్డాయి. గాయం స్పష్టమైన అసమాన అంచులు మరియు చిన్న పొలుసులను ప్రదర్శిస్తుంది. కాంటాక్ట్ డెర్మటైటిస్, తామర లేదా స్థానికీకరించిన ఫంగల్ ఇన్ఫెక్షన్ కోసం డిఫరెన్షియల్ డయాగ్నసిస్ సిఫార్సు చేయబడింది. రోగి గోకడం నివారించాలని మరియు అవసరమైనప్పుడు రోజుకు రెండుసార్లు ఓదార్పు ఎమోలియెంట్‌ను (కాలామైన్ లోషన్ లేదా తేలికపాటి హైడ్రోకార్టిసోన్ 1% క్రీమ్ వంటివి) అప్లై చేయాలని సూచించబడింది.",
    "posterior pharyngeal wall shows significant vascular congestion and diffuse erythema. tonsillar swelling is mild (grade 1) with no visible purulent exudate or cobblestoning. slight uvular inflammation noted. findings are highly consistent with acute viral pharyngitis. recommend warm saline rinses, adequate hydration, and symptomatic monitoring. suggested otc medicines: throat lozenges every 4 hours for irritation, and paracetamol (500mg up to 3 times daily as needed) for mild soreness.": "వెనుక ఫారింజియల్ గోడ గణనీయమైన వాస్కులర్ రద్దీ మరియు విస్తరించిన ఎరిథీమాను చూపుతుంది. టాన్సిలర్ వాపు తేలికపాటిగా (గ్రేట్ 1) ఉంది, ఎటువంటి చీము లేదా బొబ్బలు కనిపించలేదు. స్వల్ప యువులార్ మంట గమనించబడింది. ఫలితాలు తీవ్రమైన వైరల్ ఫారింజైటిస్‌తో ఎక్కువగా సరిపోలుతున్నాయి. వెచ్చని సెలైన్ శుభ్రం చేయుట, తగినంత హైడ్రేషన్ మరియు రోగలక్షణ పర్యవేక్షణ సిఫార్సు చేయబడింది. సూచించబడిన OTC మందులు: చికాకు కోసం ప్రతి 4 గంటలకొకసారి గొంతు మాత్రలు, మరియు తేలికపాటి గొంతు నొప్పి కోసం పారాసిటమాల్ (500mg అవసరమైన విధంగా రోజుకు 3 సార్లు).",
    "chest/skeletal radiograph analyzed. lungs demonstrate clear aeration bilateral. no consolidation, pleural effusion, or active airspace disease detected. cardiomediastinal silhouette and hila are within normal limits. skeletal structures show normal alignment with no obvious signs of acute fracture or subluxation. findings suggest normal respiratory and osseous structures. no prescription medications required. maintain normal health monitoring.": "ఛాతీ/అస్థిపంజర రేడియోగ్రాఫ్ విశ్లేషించబడింది. ఊపిరితిత్తులు రెండు వైపులా స్పష్టమైన గాలి ప్రసరణను ప్రదర్శిస్తాయి. ఎటువంటి ద్రవం చేరడం, ప్లూరల్ ఎఫ్యూషన్ లేదా క్రియాశీల ఎయిర్‌స్పేస్ వ్యాధి కనుగొనబడలేదు. కార్డియోమీడియాస్టినల్ సిల్హౌట్ మరియు హిలా సాధారణ పరిమితుల్లో ఉన్నాయి. అస్థిపంజర నిర్మాణాలు తీవ్రమైన పగుళ్లు లేదా సబ్‌లక్సేషన్ యొక్క స్పష్టమైన సంకేతాలు లేకుండా సాధారణ అమరికను చూపుతాయి. ఫలితాలు సాధారణ శ్వాసకోశ మరియు ఎముక నిర్మాణాలను సూచిస్తున్నాయి. ప్రిస్క్రిప్షన్ మందులు అవసరం లేదు. సాధారణ ఆరోగ్య పర్యవేక్షణను నిర్వహించండి.",
    "preliminary clinical imaging scan processed. general structural integrity of the target region appears unremarkable, with no clear anomalies or acute pathology visible. further specific diagnostic examinations may be required if clinical symptoms persist. mild symptoms may be managed with standard over-the-counter pain relievers or topical emollients as appropriate.": "ప్రాథమిక క్లినికల్ ఇమేజింగ్ స్కాన్ ప్రాసెస్ చేయబడింది. లక్ష్య ప్రాంతం యొక్క సాధారణ నిర్మాణాత్మక సమగ్రత సాధారణమైనదిగా కనిపిస్తుంది, ఎటువంటి స్పష్టమైన అసాధారణతలు లేదా తీవ్రమైన వ్యాధి కనిపించదు. క్లినికల్ లక్షణాలు కొనసాగితే మరింత నిర్దిష్ట రోగనిర్ధారణ పరీక్షలు కావచ్చు. తేలికపాటి లక్షణాలను అవసరమైన విధంగా ప్రామాణిక ఓవర్-ది-కౌంటర్ నొప్పి నివారణలు లేదా సమయోచిత లేపనాలతో నిర్వహించవచ్చు.",
    "apply soothing calamine lotion or mild hydrocortisone 1% cream topically twice daily as needed. avoid scratching.": "అవసరమైన విధంగా రోజుకు రెండుసార్లు కాలామైన్ లోషన్ లేదా తేలికపాటి హైడ్రోకార్టిసోన్ 1% క్రీమ్ అప్లై చేయండి. గోకడం నివారించండి.",
    "warm saline gargles, throat lozenges every 4 hours, and paracetamol 500mg up to 3 times daily as needed.": "వెచ్చని సెలైన్ గార్గ్లింగ్, ప్రతి 4 గంటలకొకసారి గొంతు మాత్రలు, మరియు అవసరమైన విధంగా రోజుకు 3 సార్లు పారాసిటమాల్ 500mg.",
    "no active airspace disease or fracture detected. maintain routine health checks.": "ఎటువంటి క్రియాశీల ఎయిర్‌స్పేస్ వ్యాధి లేదా పగుళ్లు కనుగొనబడలేదు. సాధారణ ఆరోగ్య పరీక్షలను నిర్వహించండి.",
    "no acute pathology visible. follow up if symptoms persist.": "ఎటువంటి తీవ్రమైన వ్యాధి కనిపించదు. లక్షణాలు కొనసాగితే తదుపరి సంప్రదింపులు జరపండి.",
    "standard clinical disclaimer: this ai-generated report is for informational purposes only. it does not replace professional medical advice, diagnosis, or treatment. please consult a qualified healthcare provider before starting any new medication or treatment plan.": "ప్రాథమిక క్లినికల్ నిరాకరణ: ఈ AI-ఉత్పత్తి చేసిన నివేదిక సమాచార ప్రయోజనాల కోసం మాత్రమే. ఇది వృత్తిపరమైన వైద్య సలహా, నిర్ధారణ లేదా చికిత్సకు ప్రత్యామ్నాయం కాదు. దయచేసి ఏదైనా కొత్త మందులు లేదా చికిత్స ప్రణాళికను ప్రారంభించే ముందు అర్హత కలిగిన ఆరోగ్య సంరక్షణ ప్రదాతని సంప్రదించండి.",
    "welcome": "స్వాగతం",
    "account initialized. no appointments booked yet.": "ఖాతా ప్రారంభించబడింది. ఇంకా అపాయింట్‌మెంట్‌లు బుక్ చేయబడలేదు."
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('app_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_lang', currentLanguage);
  }, [currentLanguage]);

  const t = (key) => {
    if (!key || typeof key !== 'string') return key;
    
    // Check if the key exists directly in translations
    const langDict = translations[currentLanguage] || translations['en'];
    if (langDict[key]) return langDict[key];
    
    // Perform case-insensitive match or custom name transliteration
    const normalizedKey = key.trim().toLowerCase();
    
    if (currentLanguage !== 'en' && nameTranslations[currentLanguage]) {
      let isDoctor = false;
      let cleanName = key.trim();
      
      if (normalizedKey.startsWith("dr.") || normalizedKey.startsWith("dr ")) {
        isDoctor = true;
        cleanName = cleanName.replace(/^dr\.?\s+/i, "");
      }
      
      const cleanNormalized = cleanName.toLowerCase();
      const nameDict = nameTranslations[currentLanguage];
      let translated = nameDict[cleanNormalized];
      
      if (!translated) {
        const words = cleanNormalized.split(/\s+/);
        const translatedWords = words.map(w => nameDict[w] || w);
        if (translatedWords.some((w, idx) => w !== words[idx])) {
          translated = translatedWords.join(" ");
        }
      }
      
      if (translated) {
        if (isDoctor) {
          const prefix = currentLanguage === 'hi' ? "डॉ. " : "డా. ";
          return prefix + translated;
        }
        return translated;
      }
    }

    return translations['en'][key] || key;
  };

  const translateClinicalText = (text) => {
    if (!text) return '';
    const paragraphs = text.split('\n');
    return paragraphs.map(para => {
      const trimmed = para.trim();
      if (!trimmed) return '';
      
      if (trimmed.startsWith('Primary Finding:')) {
        let val = trimmed.replace('Primary Finding:', '').trim();
        let confidenceStr = '';
        const confMatch = val.match(/\\(Confidence:\\s*(\\d+(\\.\\d+)?%)\\)/i) || val.match(/\(Confidence:\s*(\d+(\.\d+)?%)\)/i);
        if (confMatch) {
          const confidenceLabel = t('confidenceLabel') || 'Confidence';
          confidenceStr = ` (${confidenceLabel}: ${confMatch[1]})`;
          val = val.replace(confMatch[0], '').trim();
        }
        const label = t('primaryFindingLabel') || 'Primary Finding';
        return `${label}: ${t(val)}${confidenceStr}`;
      }
      if (trimmed.startsWith('Severity Level:')) {
        const val = trimmed.replace('Severity Level:', '').trim();
        const label = t('severityLevelLabel') || 'Severity Level';
        return `${label}: ${t(val)}`;
      }
      if (trimmed.startsWith('Clinical Recommendation:')) {
        const val = trimmed.replace('Clinical Recommendation:', '').trim();
        const label = t('clinicalRecommendationLabel') || 'Clinical Recommendation';
        return `${label}: ${t(val)}`;
      }
      return t(trimmed);
    }).join('\n');
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setCurrentLanguage, t, translateClinicalText }}>
      {children}
    </LanguageContext.Provider>
  );
};
